// Code generated by ogen, DO NOT EDIT.

package v1

// OperationName is the ogen operation name
type OperationName = string

const (
	SegApplyOperation                   OperationName = "SegApply"
	SegCreateOperation                  OperationName = "SegCreate"
	SegDeleteOperation                  OperationName = "SegDelete"
	SegGetOperation                     OperationName = "SegGet"
	SegInterfaceGetInterfaceOperation   OperationName = "SegInterfaceGetInterface"
	SegListOperation                    OperationName = "SegList"
	SegStatusDeletePowerStatusOperation OperationName = "SegStatusDeletePowerStatus"
	SegStatusGetPowerStatusOperation    OperationName = "SegStatusGetPowerStatus"
	SegStatusResetPowerStatusOperation  OperationName = "SegStatusResetPowerStatus"
	SegStatusUpdatePowerStatusOperation OperationName = "SegStatusUpdatePowerStatus"
	SegUpdateOperation                  OperationName = "SegUpdate"
)
