// Code generated by ogen, DO NOT EDIT.

package v1

import (
	"time"

	"github.com/google/uuid"
)

// SetFake set fake values.
func (s *AlertProject) SetFake() {
	{
		{
			s.ID = int64(0)
		}
	}
	{
		{
			s.Name.SetFake()
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.Tags = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.Tags = append(s.Tags, elem)
			}
		}
	}
	{
		{
			s.Icon.SetFake()
		}
	}
	{
		{
			s.AccountID = "string"
		}
	}
	{
		{
			s.ResourceID.SetFake()
		}
	}
	{
		{
			s.CreatedAt = time.Now()
		}
	}
	{
		{
			s.RulesURL = "string"
		}
	}
	{
		{
			s.NotificationTargetsURL = "string"
		}
	}
	{
		{
			s.NotificationRoutingsURL = "string"
		}
	}
	{
		{
			s.HistoriesURL = "string"
		}
	}
	{
		{
			s.LogMeasureRulesURL = "string"
		}
	}
}

// SetFake set fake values.
func (s *AlertProjectCreate) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *AlertProjectIcon) SetFake() {
	{
		{
			s.ID.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *AlertRule) SetFake() {
	{
		{
			s.UID = uuid.New()
		}
	}
	{
		{
			s.ProjectID.SetFake()
		}
	}
	{
		{
			s.MetricsStorageID.SetFake()
		}
	}
	{
		{
			s.Name.SetFake()
		}
	}
	{
		{
			s.Query = "string"
		}
	}
	{
		{
			s.Format.SetFake()
		}
	}
	{
		{
			s.Template.SetFake()
		}
	}
	{
		{
			s.Open = true
		}
	}
	{
		{
			s.EnabledWarning.SetFake()
		}
	}
	{
		{
			s.EnabledCritical.SetFake()
		}
	}
	{
		{
			s.ThresholdWarning.SetFake()
		}
	}
	{
		{
			s.ThresholdCritical.SetFake()
		}
	}
	{
		{
			s.ThresholdDurationWarning.SetFake()
		}
	}
	{
		{
			s.ThresholdDurationCritical.SetFake()
		}
	}
	{
		{
			s.HistoryURL = "string"
		}
	}
}

// SetFake set fake values.
func (s *AndMatcher) SetFake() {
	{
		{
			s.Type.SetFake()
		}
	}
	{
		{
			s.Matchers = nil
			for i := 0; i < 0; i++ {
				var elem FieldMatcher
				{
					elem.SetFake()
				}
				s.Matchers = append(s.Matchers, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *DashboardProject) SetFake() {
	{
		{
			s.ID = int64(0)
		}
	}
	{
		{
			s.Name.SetFake()
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.Tags = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.Tags = append(s.Tags, elem)
			}
		}
	}
	{
		{
			s.Icon.SetFake()
		}
	}
	{
		{
			s.AccountID = "string"
		}
	}
	{
		{
			s.ResourceID.SetFake()
		}
	}
	{
		{
			s.CreatedAt = time.Now()
		}
	}
}

// SetFake set fake values.
func (s *DashboardProjectCreate) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *DashboardProjectIcon) SetFake() {
	{
		{
			s.ID.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *EnumMatcher) SetFake() {
	{
		{
			s.Type.SetFake()
		}
	}
	{
		{
			s.Field.SetFake()
		}
	}
	{
		{
			s.Value = nil
			for i := 0; i < 0; i++ {
				var elem ValueEnum
				{
					elem.SetFake()
				}
				s.Value = append(s.Value, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *FieldMatcher) SetFake() {
	var variant AndMatcher

	{
		variant.SetFake()
	}
	s.SetAndMatcher(variant)
}

// SetFake set fake values.
func (s *FieldModel) SetFake() {
	*s = FieldModelSeverity
}

// SetFake set fake values.
func (s *History) SetFake() {
	{
		{
			s.UID = uuid.New()
		}
	}
	{
		{
			s.ProjectID = int64(0)
		}
	}
	{
		{
			s.RuleUID = "string"
		}
	}
	{
		{
			s.StartsAt = time.Now()
		}
	}
	{
		{
			s.EndsAt.SetFake()
		}
	}
	{
		{
			s.Open = true
		}
	}
	{
		{
			s.Labels = "string"
		}
	}
	{
		{
			s.Severity.SetFake()
		}
	}
	{
		{
			s.Query.SetFake()
		}
	}
	{
		{
			s.Threshold.SetFake()
		}
	}
	{
		{
			s.Value.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *HistorySeverity) SetFake() {
	*s = HistorySeverityWarning
}

// SetFake set fake values.
func (s *LogMeasureRule) SetFake() {
	{
		{
			s.ID = int64(0)
		}
	}
	{
		{
			s.UID = uuid.New()
		}
	}
	{
		{
			s.ProjectID.SetFake()
		}
	}
	{
		{
			s.Name.SetFake()
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.LogStorage.SetFake()
		}
	}
	{
		{
			s.LogStorageID.SetFake()
		}
	}
	{
		{
			s.MetricsStorage.SetFake()
		}
	}
	{
		{
			s.MetricsStorageID.SetFake()
		}
	}
	{
		{
			s.Rule.SetFake()
		}
	}
	{
		{
			s.CreatedAt = time.Now()
		}
	}
	{
		{
			s.UpdatedAt = time.Now()
		}
	}
}

// SetFake set fake values.
func (s *LogMeasureRuleModel) SetFake() {
	{
		{
			s.Version.SetFake()
		}
	}
	{
		{
			s.Query.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *LogMeasureRuleV1) SetFake() {
	{
		{
			s.Matchers = nil
			for i := 0; i < 0; i++ {
				var elem FieldMatcher
				{
					elem.SetFake()
				}
				s.Matchers = append(s.Matchers, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *LogMeasureRuleVersionEnum) SetFake() {
	*s = LogMeasureRuleVersionEnumV1
}

// SetFake set fake values.
func (s *LogRouting) SetFake() {
	{
		{
			s.ID = int64(0)
		}
	}
	{
		{
			s.UID = uuid.New()
		}
	}
	{
		{
			s.ResourceID.SetFake()
		}
	}
	{
		{
			s.Publisher.SetFake()
		}
	}
	{
		{
			s.PublisherCode.SetFake()
		}
	}
	{
		{
			s.Variant = "string"
		}
	}
	{
		{
			s.LogStorage.SetFake()
		}
	}
	{
		{
			s.LogStorageID.SetFake()
		}
	}
	{
		{
			s.CreatedAt = time.Now()
		}
	}
	{
		{
			s.UpdatedAt = time.Now()
		}
	}
}

// SetFake set fake values.
func (s *LogStorage) SetFake() {
	{
		{
			s.ID = int64(0)
		}
	}
	{
		{
			s.Name.SetFake()
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.Tags = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.Tags = append(s.Tags, elem)
			}
		}
	}
	{
		{
			s.Icon.SetFake()
		}
	}
	{
		{
			s.ExpireDay.SetFake()
		}
	}
	{
		{
			s.CreatedAt = time.Now()
		}
	}
	{
		{
			s.Endpoints.SetFake()
		}
	}
	{
		{
			s.AccountID = "string"
		}
	}
	{
		{
			s.ResourceID.SetFake()
		}
	}
	{
		{
			s.IsSystem = true
		}
	}
	{
		{
			s.Usage.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *LogStorageAccessKey) SetFake() {
	{
		{
			s.ID = int64(0)
		}
	}
	{
		{
			s.UID = uuid.New()
		}
	}
	{
		{
			s.Secret = uuid.New()
		}
	}
	{
		{
			s.Token = "string"
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *LogStorageCreate) SetFake() {
	{
		{
			s.Classification.SetFake()
		}
	}
	{
		{
			s.IsSystem = true
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *LogStorageCreateClassification) SetFake() {
	*s = LogStorageCreateClassificationShared
}

// SetFake set fake values.
func (s *LogStorageEndpoints) SetFake() {
	{
		{
			s.Ingester.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *LogStorageEndpointsIngester) SetFake() {
	{
		{
			s.Address = "string"
		}
	}
	{
		{
			s.Insecure.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *LogStorageIcon) SetFake() {
	{
		{
			s.ID.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *LogStorageUsage) SetFake() {
	{
		{
			s.LogRoutings = int(0)
		}
	}
	{
		{
			s.LogMeasureRules = int(0)
		}
	}
}

// SetFake set fake values.
func (s *MapFieldName) SetFake() {
	*s = MapFieldNameResourceLabels
}

// SetFake set fake values.
func (s *MapKeyExistsMatcher) SetFake() {
	{
		{
			s.Type.SetFake()
		}
	}
	{
		{
			s.Field.SetFake()
		}
	}
	{
		{
			s.Key = "string"
		}
	}
}

// SetFake set fake values.
func (s *MapKeyValueMatcher) SetFake() {
	{
		{
			s.Type.SetFake()
		}
	}
	{
		{
			s.Field.SetFake()
		}
	}
	{
		{
			s.Key = "string"
		}
	}
	{
		{
			s.Value = "string"
		}
	}
}

// SetFake set fake values.
func (s *MatchLabelsItem) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Value = "string"
		}
	}
}

// SetFake set fake values.
func (s *MetricsRouting) SetFake() {
	{
		{
			s.ID = int64(0)
		}
	}
	{
		{
			s.UID = uuid.New()
		}
	}
	{
		{
			s.ResourceID.SetFake()
		}
	}
	{
		{
			s.Publisher.SetFake()
		}
	}
	{
		{
			s.PublisherCode.SetFake()
		}
	}
	{
		{
			s.Variant = "string"
		}
	}
	{
		{
			s.MetricsStorage.SetFake()
		}
	}
	{
		{
			s.MetricsStorageID.SetFake()
		}
	}
	{
		{
			s.CreatedAt = time.Now()
		}
	}
	{
		{
			s.UpdatedAt = time.Now()
		}
	}
}

// SetFake set fake values.
func (s *MetricsStorage) SetFake() {
	{
		{
			s.ID = int64(0)
		}
	}
	{
		{
			s.Name.SetFake()
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.Tags = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.Tags = append(s.Tags, elem)
			}
		}
	}
	{
		{
			s.Icon.SetFake()
		}
	}
	{
		{
			s.IsSystem = true
		}
	}
	{
		{
			s.AccountID = "string"
		}
	}
	{
		{
			s.ResourceID.SetFake()
		}
	}
	{
		{
			s.Endpoints.SetFake()
		}
	}
	{
		{
			s.CreatedAt = time.Now()
		}
	}
	{
		{
			s.UpdatedAt = time.Now()
		}
	}
	{
		{
			s.Usage.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *MetricsStorageAccessKey) SetFake() {
	{
		{
			s.ID = int64(0)
		}
	}
	{
		{
			s.UID = uuid.New()
		}
	}
	{
		{
			s.Secret = uuid.New()
		}
	}
	{
		{
			s.Token = "string"
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *MetricsStorageCreate) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.IsSystem = true
		}
	}
}

// SetFake set fake values.
func (s *MetricsStorageEndpoints) SetFake() {
	{
		{
			s.Address = "string"
		}
	}
}

// SetFake set fake values.
func (s *MetricsStorageIcon) SetFake() {
	{
		{
			s.ID.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *MetricsStorageUsage) SetFake() {
	{
		{
			s.MetricsRoutings = int(0)
		}
	}
	{
		{
			s.AlertRules = int(0)
		}
	}
	{
		{
			s.LogMeasureRules = int(0)
		}
	}
}

// SetFake set fake values.
func (s *NilAlertProjectIcon) SetFake() {
	s.Null = true
}

// SetFake set fake values.
func (s *NilDashboardProjectIcon) SetFake() {
	s.Null = true
}

// SetFake set fake values.
func (s *NilInt64) SetFake() {
	s.Null = true
}

// SetFake set fake values.
func (s *NilLogStorageIcon) SetFake() {
	s.Null = true
}

// SetFake set fake values.
func (s *NilMetricsStorageIcon) SetFake() {
	s.Null = true
}

// SetFake set fake values.
func (s *NilTraceStorageIcon) SetFake() {
	s.Null = true
}

// SetFake set fake values.
func (s *NilWrappedAlertProjectIcon) SetFake() {
	s.Null = true
}

// SetFake set fake values.
func (s *NilWrappedDashboardProjectIcon) SetFake() {
	s.Null = true
}

// SetFake set fake values.
func (s *NilWrappedLogStorageIcon) SetFake() {
	s.Null = true
}

// SetFake set fake values.
func (s *NilWrappedMetricsStorageIcon) SetFake() {
	s.Null = true
}

// SetFake set fake values.
func (s *NilWrappedTraceStorageIcon) SetFake() {
	s.Null = true
}

// SetFake set fake values.
func (s *NotificationRouting) SetFake() {
	{
		{
			s.UID = uuid.New()
		}
	}
	{
		{
			s.ProjectID.SetFake()
		}
	}
	{
		{
			s.NotificationTarget.SetFake()
		}
	}
	{
		{
			s.NotificationTargetUID.SetFake()
		}
	}
	{
		{
			s.MatchLabels = nil
			for i := 0; i < 0; i++ {
				var elem MatchLabelsItem
				{
					elem.SetFake()
				}
				s.MatchLabels = append(s.MatchLabels, elem)
			}
		}
	}
	{
		{
			s.ResendIntervalMinutes.SetFake()
		}
	}
	{
		{
			s.Order.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *NotificationRoutingOrder) SetFake() {
	{
		{
			s.NotificationRoutingUID = uuid.New()
		}
	}
	{
		{
			s.Order = int(0)
		}
	}
}

// SetFake set fake values.
func (s *NotificationTarget) SetFake() {
	{
		{
			s.UID = uuid.New()
		}
	}
	{
		{
			s.ProjectID.SetFake()
		}
	}
	{
		{
			s.ServiceType.SetFake()
		}
	}
	{
		{
			s.URL = "string"
		}
	}
	{
		{
			s.Config.SetFake()
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *NotificationTargetConfig) SetFake() {
}

// SetFake set fake values.
func (s *NotificationTargetServiceType) SetFake() {
	*s = NotificationTargetServiceTypeSAKURASIMPLENOTICE
}

// SetFake set fake values.
func (s *NumMatcher) SetFake() {
	{
		{
			s.Type.SetFake()
		}
	}
	{
		{
			s.Operator.SetFake()
		}
	}
	{
		{
			s.Field.SetFake()
		}
	}
	{
		{
			s.Value = float64(0)
		}
	}
	{
		{
			s.ValueList = nil
			for i := 0; i < 0; i++ {
				var elem float64
				{
					elem = float64(0)
				}
				s.ValueList = append(s.ValueList, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *NumberFieldName) SetFake() {
	*s = NumberFieldNameHTTPRequestSize
}

// SetFake set fake values.
func (s *Operator) SetFake() {
	*s = OperatorEq
}

// SetFake set fake values.
func (s *Operator1) SetFake() {
	*s = Operator1Eq
}

// SetFake set fake values.
func (s *OptAlertProject) SetFake() {
	var elem AlertProject
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptBool) SetFake() {
	var elem bool
	{
		elem = true
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptDashboardProject) SetFake() {
	var elem DashboardProject
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptDateTime) SetFake() {
	var elem time.Time
	{
		elem = time.Now()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptFloat64) SetFake() {
	var elem float64
	{
		elem = float64(0)
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptInt) SetFake() {
	var elem int
	{
		elem = int(0)
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptInt64) SetFake() {
	var elem int64
	{
		elem = int64(0)
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptLogMeasureRuleModel) SetFake() {
	var elem LogMeasureRuleModel
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptLogStorage) SetFake() {
	var elem LogStorage
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptLogStorageAccessKey) SetFake() {
	var elem LogStorageAccessKey
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptLogStorageCreateClassification) SetFake() {
	var elem LogStorageCreateClassification
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptMetricsStorage) SetFake() {
	var elem MetricsStorage
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptMetricsStorageAccessKey) SetFake() {
	var elem MetricsStorageAccessKey
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptNilDateTime) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilInt64) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilPatchedAlertProjectIcon) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilPatchedDashboardProjectIcon) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilPatchedLogStorageIcon) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilPatchedMetricsStorageIcon) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilPatchedTraceStorageIcon) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilString) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNotificationTarget) SetFake() {
	var elem NotificationTarget
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptPatchedAlertProject) SetFake() {
	var elem PatchedAlertProject
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptPatchedAlertRule) SetFake() {
	var elem PatchedAlertRule
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptPatchedDashboardProject) SetFake() {
	var elem PatchedDashboardProject
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptPatchedLogMeasureRule) SetFake() {
	var elem PatchedLogMeasureRule
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptPatchedLogRouting) SetFake() {
	var elem PatchedLogRouting
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptPatchedLogStorage) SetFake() {
	var elem PatchedLogStorage
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptPatchedLogStorageAccessKey) SetFake() {
	var elem PatchedLogStorageAccessKey
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptPatchedLogStorageEndpoints) SetFake() {
	var elem PatchedLogStorageEndpoints
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptPatchedLogStorageUsage) SetFake() {
	var elem PatchedLogStorageUsage
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptPatchedMetricsRouting) SetFake() {
	var elem PatchedMetricsRouting
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptPatchedMetricsStorage) SetFake() {
	var elem PatchedMetricsStorage
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptPatchedMetricsStorageAccessKey) SetFake() {
	var elem PatchedMetricsStorageAccessKey
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptPatchedMetricsStorageEndpoints) SetFake() {
	var elem PatchedMetricsStorageEndpoints
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptPatchedMetricsStorageUsage) SetFake() {
	var elem PatchedMetricsStorageUsage
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptPatchedNotificationRouting) SetFake() {
	var elem PatchedNotificationRouting
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptPatchedNotificationTarget) SetFake() {
	var elem PatchedNotificationTarget
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptPatchedNotificationTargetServiceType) SetFake() {
	var elem PatchedNotificationTargetServiceType
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptPatchedTraceStorage) SetFake() {
	var elem PatchedTraceStorage
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptPatchedTraceStorageAccessKey) SetFake() {
	var elem PatchedTraceStorageAccessKey
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptPatchedTraceStorageEndpoints) SetFake() {
	var elem PatchedTraceStorageEndpoints
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptProvisioningCreate) SetFake() {
	var elem ProvisioningCreate
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptProvisioningExist) SetFake() {
	var elem ProvisioningExist
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptPublisher) SetFake() {
	var elem Publisher
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptString) SetFake() {
	var elem string
	{
		elem = "string"
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptTraceStorage) SetFake() {
	var elem TraceStorage
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptTraceStorageAccessKey) SetFake() {
	var elem TraceStorageAccessKey
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptTraceStorageCreateClassification) SetFake() {
	var elem TraceStorageCreateClassification
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptUUID) SetFake() {
	var elem uuid.UUID
	{
		elem = uuid.New()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OrMatcher) SetFake() {
	{
		{
			s.Type.SetFake()
		}
	}
	{
		{
			s.Matchers = nil
			for i := 0; i < 0; i++ {
				var elem FieldMatcher
				{
					elem.SetFake()
				}
				s.Matchers = append(s.Matchers, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *PaginatedAlertProjectList) SetFake() {
	{
		{
			s.Count = int64(0)
		}
	}
	{
		{
			s.From = int64(0)
		}
	}
	{
		{
			s.Total = int64(0)
		}
	}
	{
		{
			s.IsOk.SetFake()
		}
	}
	{
		{
			s.Results = nil
			for i := 0; i < 0; i++ {
				var elem AlertProject
				{
					elem.SetFake()
				}
				s.Results = append(s.Results, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *PaginatedAlertRuleList) SetFake() {
	{
		{
			s.Count = int64(0)
		}
	}
	{
		{
			s.From = int64(0)
		}
	}
	{
		{
			s.Total = int64(0)
		}
	}
	{
		{
			s.IsOk.SetFake()
		}
	}
	{
		{
			s.Results = nil
			for i := 0; i < 0; i++ {
				var elem AlertRule
				{
					elem.SetFake()
				}
				s.Results = append(s.Results, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *PaginatedDashboardProjectList) SetFake() {
	{
		{
			s.Count = int64(0)
		}
	}
	{
		{
			s.From = int64(0)
		}
	}
	{
		{
			s.Total = int64(0)
		}
	}
	{
		{
			s.IsOk.SetFake()
		}
	}
	{
		{
			s.Results = nil
			for i := 0; i < 0; i++ {
				var elem DashboardProject
				{
					elem.SetFake()
				}
				s.Results = append(s.Results, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *PaginatedHistoryList) SetFake() {
	{
		{
			s.Count = int64(0)
		}
	}
	{
		{
			s.From = int64(0)
		}
	}
	{
		{
			s.Total = int64(0)
		}
	}
	{
		{
			s.IsOk.SetFake()
		}
	}
	{
		{
			s.Results = nil
			for i := 0; i < 0; i++ {
				var elem History
				{
					elem.SetFake()
				}
				s.Results = append(s.Results, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *PaginatedLogMeasureRuleList) SetFake() {
	{
		{
			s.Count = int64(0)
		}
	}
	{
		{
			s.From = int64(0)
		}
	}
	{
		{
			s.Total = int64(0)
		}
	}
	{
		{
			s.IsOk.SetFake()
		}
	}
	{
		{
			s.Results = nil
			for i := 0; i < 0; i++ {
				var elem LogMeasureRule
				{
					elem.SetFake()
				}
				s.Results = append(s.Results, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *PaginatedLogRoutingList) SetFake() {
	{
		{
			s.Count = int64(0)
		}
	}
	{
		{
			s.From = int64(0)
		}
	}
	{
		{
			s.Total = int64(0)
		}
	}
	{
		{
			s.IsOk.SetFake()
		}
	}
	{
		{
			s.Results = nil
			for i := 0; i < 0; i++ {
				var elem LogRouting
				{
					elem.SetFake()
				}
				s.Results = append(s.Results, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *PaginatedLogStorageAccessKeyList) SetFake() {
	{
		{
			s.Count = int64(0)
		}
	}
	{
		{
			s.From = int64(0)
		}
	}
	{
		{
			s.Total = int64(0)
		}
	}
	{
		{
			s.IsOk.SetFake()
		}
	}
	{
		{
			s.Results = nil
			for i := 0; i < 0; i++ {
				var elem LogStorageAccessKey
				{
					elem.SetFake()
				}
				s.Results = append(s.Results, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *PaginatedLogStorageList) SetFake() {
	{
		{
			s.Count = int64(0)
		}
	}
	{
		{
			s.From = int64(0)
		}
	}
	{
		{
			s.Total = int64(0)
		}
	}
	{
		{
			s.IsOk.SetFake()
		}
	}
	{
		{
			s.Results = nil
			for i := 0; i < 0; i++ {
				var elem LogStorage
				{
					elem.SetFake()
				}
				s.Results = append(s.Results, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *PaginatedMetricsRoutingList) SetFake() {
	{
		{
			s.Count = int64(0)
		}
	}
	{
		{
			s.From = int64(0)
		}
	}
	{
		{
			s.Total = int64(0)
		}
	}
	{
		{
			s.IsOk.SetFake()
		}
	}
	{
		{
			s.Results = nil
			for i := 0; i < 0; i++ {
				var elem MetricsRouting
				{
					elem.SetFake()
				}
				s.Results = append(s.Results, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *PaginatedMetricsStorageAccessKeyList) SetFake() {
	{
		{
			s.Count = int64(0)
		}
	}
	{
		{
			s.From = int64(0)
		}
	}
	{
		{
			s.Total = int64(0)
		}
	}
	{
		{
			s.IsOk.SetFake()
		}
	}
	{
		{
			s.Results = nil
			for i := 0; i < 0; i++ {
				var elem MetricsStorageAccessKey
				{
					elem.SetFake()
				}
				s.Results = append(s.Results, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *PaginatedMetricsStorageList) SetFake() {
	{
		{
			s.Count = int64(0)
		}
	}
	{
		{
			s.From = int64(0)
		}
	}
	{
		{
			s.Total = int64(0)
		}
	}
	{
		{
			s.IsOk.SetFake()
		}
	}
	{
		{
			s.Results = nil
			for i := 0; i < 0; i++ {
				var elem MetricsStorage
				{
					elem.SetFake()
				}
				s.Results = append(s.Results, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *PaginatedNotificationRoutingList) SetFake() {
	{
		{
			s.Count = int64(0)
		}
	}
	{
		{
			s.From = int64(0)
		}
	}
	{
		{
			s.Total = int64(0)
		}
	}
	{
		{
			s.IsOk.SetFake()
		}
	}
	{
		{
			s.Results = nil
			for i := 0; i < 0; i++ {
				var elem NotificationRouting
				{
					elem.SetFake()
				}
				s.Results = append(s.Results, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *PaginatedNotificationTargetList) SetFake() {
	{
		{
			s.Count = int64(0)
		}
	}
	{
		{
			s.From = int64(0)
		}
	}
	{
		{
			s.Total = int64(0)
		}
	}
	{
		{
			s.IsOk.SetFake()
		}
	}
	{
		{
			s.Results = nil
			for i := 0; i < 0; i++ {
				var elem NotificationTarget
				{
					elem.SetFake()
				}
				s.Results = append(s.Results, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *PaginatedPublisherList) SetFake() {
	{
		{
			s.Count = int64(0)
		}
	}
	{
		{
			s.From = int64(0)
		}
	}
	{
		{
			s.Total = int64(0)
		}
	}
	{
		{
			s.IsOk.SetFake()
		}
	}
	{
		{
			s.Results = nil
			for i := 0; i < 0; i++ {
				var elem Publisher
				{
					elem.SetFake()
				}
				s.Results = append(s.Results, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *PaginatedTraceStorageAccessKeyList) SetFake() {
	{
		{
			s.Count = int64(0)
		}
	}
	{
		{
			s.From = int64(0)
		}
	}
	{
		{
			s.Total = int64(0)
		}
	}
	{
		{
			s.IsOk.SetFake()
		}
	}
	{
		{
			s.Results = nil
			for i := 0; i < 0; i++ {
				var elem TraceStorageAccessKey
				{
					elem.SetFake()
				}
				s.Results = append(s.Results, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *PaginatedTraceStorageList) SetFake() {
	{
		{
			s.Count = int64(0)
		}
	}
	{
		{
			s.From = int64(0)
		}
	}
	{
		{
			s.Total = int64(0)
		}
	}
	{
		{
			s.IsOk.SetFake()
		}
	}
	{
		{
			s.Results = nil
			for i := 0; i < 0; i++ {
				var elem TraceStorage
				{
					elem.SetFake()
				}
				s.Results = append(s.Results, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *PatchedAlertProject) SetFake() {
	{
		{
			s.ID.SetFake()
		}
	}
	{
		{
			s.Name.SetFake()
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.Tags = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.Tags = append(s.Tags, elem)
			}
		}
	}
	{
		{
			s.Icon.SetFake()
		}
	}
	{
		{
			s.AccountID.SetFake()
		}
	}
	{
		{
			s.ResourceID.SetFake()
		}
	}
	{
		{
			s.CreatedAt.SetFake()
		}
	}
	{
		{
			s.RulesURL.SetFake()
		}
	}
	{
		{
			s.NotificationTargetsURL.SetFake()
		}
	}
	{
		{
			s.NotificationRoutingsURL.SetFake()
		}
	}
	{
		{
			s.HistoriesURL.SetFake()
		}
	}
	{
		{
			s.LogMeasureRulesURL.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PatchedAlertProjectIcon) SetFake() {
	{
		{
			s.ID.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PatchedAlertRule) SetFake() {
	{
		{
			s.UID.SetFake()
		}
	}
	{
		{
			s.ProjectID.SetFake()
		}
	}
	{
		{
			s.MetricsStorageID.SetFake()
		}
	}
	{
		{
			s.Name.SetFake()
		}
	}
	{
		{
			s.Query.SetFake()
		}
	}
	{
		{
			s.Format.SetFake()
		}
	}
	{
		{
			s.Template.SetFake()
		}
	}
	{
		{
			s.Open.SetFake()
		}
	}
	{
		{
			s.EnabledWarning.SetFake()
		}
	}
	{
		{
			s.EnabledCritical.SetFake()
		}
	}
	{
		{
			s.ThresholdWarning.SetFake()
		}
	}
	{
		{
			s.ThresholdCritical.SetFake()
		}
	}
	{
		{
			s.ThresholdDurationWarning.SetFake()
		}
	}
	{
		{
			s.ThresholdDurationCritical.SetFake()
		}
	}
	{
		{
			s.HistoryURL.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PatchedDashboardProject) SetFake() {
	{
		{
			s.ID.SetFake()
		}
	}
	{
		{
			s.Name.SetFake()
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.Tags = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.Tags = append(s.Tags, elem)
			}
		}
	}
	{
		{
			s.Icon.SetFake()
		}
	}
	{
		{
			s.AccountID.SetFake()
		}
	}
	{
		{
			s.ResourceID.SetFake()
		}
	}
	{
		{
			s.CreatedAt.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PatchedDashboardProjectIcon) SetFake() {
	{
		{
			s.ID.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PatchedLogMeasureRule) SetFake() {
	{
		{
			s.ID.SetFake()
		}
	}
	{
		{
			s.UID.SetFake()
		}
	}
	{
		{
			s.ProjectID.SetFake()
		}
	}
	{
		{
			s.Name.SetFake()
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.LogStorage.SetFake()
		}
	}
	{
		{
			s.LogStorageID.SetFake()
		}
	}
	{
		{
			s.MetricsStorage.SetFake()
		}
	}
	{
		{
			s.MetricsStorageID.SetFake()
		}
	}
	{
		{
			s.Rule.SetFake()
		}
	}
	{
		{
			s.CreatedAt.SetFake()
		}
	}
	{
		{
			s.UpdatedAt.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PatchedLogRouting) SetFake() {
	{
		{
			s.ID.SetFake()
		}
	}
	{
		{
			s.UID.SetFake()
		}
	}
	{
		{
			s.ResourceID.SetFake()
		}
	}
	{
		{
			s.Publisher.SetFake()
		}
	}
	{
		{
			s.PublisherCode.SetFake()
		}
	}
	{
		{
			s.Variant.SetFake()
		}
	}
	{
		{
			s.LogStorage.SetFake()
		}
	}
	{
		{
			s.LogStorageID.SetFake()
		}
	}
	{
		{
			s.CreatedAt.SetFake()
		}
	}
	{
		{
			s.UpdatedAt.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PatchedLogStorage) SetFake() {
	{
		{
			s.ID.SetFake()
		}
	}
	{
		{
			s.Name.SetFake()
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.Tags = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.Tags = append(s.Tags, elem)
			}
		}
	}
	{
		{
			s.Icon.SetFake()
		}
	}
	{
		{
			s.ExpireDay.SetFake()
		}
	}
	{
		{
			s.CreatedAt.SetFake()
		}
	}
	{
		{
			s.Endpoints.SetFake()
		}
	}
	{
		{
			s.AccountID.SetFake()
		}
	}
	{
		{
			s.ResourceID.SetFake()
		}
	}
	{
		{
			s.IsSystem.SetFake()
		}
	}
	{
		{
			s.Usage.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PatchedLogStorageAccessKey) SetFake() {
	{
		{
			s.ID.SetFake()
		}
	}
	{
		{
			s.UID.SetFake()
		}
	}
	{
		{
			s.Secret.SetFake()
		}
	}
	{
		{
			s.Token.SetFake()
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PatchedLogStorageEndpoints) SetFake() {
	{
		{
			s.Ingester.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PatchedLogStorageEndpointsIngester) SetFake() {
	{
		{
			s.Address = "string"
		}
	}
	{
		{
			s.Insecure.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PatchedLogStorageIcon) SetFake() {
	{
		{
			s.ID.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PatchedLogStorageUsage) SetFake() {
	{
		{
			s.LogRoutings = int(0)
		}
	}
	{
		{
			s.LogMeasureRules = int(0)
		}
	}
}

// SetFake set fake values.
func (s *PatchedMetricsRouting) SetFake() {
	{
		{
			s.ID.SetFake()
		}
	}
	{
		{
			s.UID.SetFake()
		}
	}
	{
		{
			s.ResourceID.SetFake()
		}
	}
	{
		{
			s.Publisher.SetFake()
		}
	}
	{
		{
			s.PublisherCode.SetFake()
		}
	}
	{
		{
			s.Variant.SetFake()
		}
	}
	{
		{
			s.MetricsStorage.SetFake()
		}
	}
	{
		{
			s.MetricsStorageID.SetFake()
		}
	}
	{
		{
			s.CreatedAt.SetFake()
		}
	}
	{
		{
			s.UpdatedAt.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PatchedMetricsStorage) SetFake() {
	{
		{
			s.ID.SetFake()
		}
	}
	{
		{
			s.Name.SetFake()
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.Tags = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.Tags = append(s.Tags, elem)
			}
		}
	}
	{
		{
			s.Icon.SetFake()
		}
	}
	{
		{
			s.IsSystem.SetFake()
		}
	}
	{
		{
			s.AccountID.SetFake()
		}
	}
	{
		{
			s.ResourceID.SetFake()
		}
	}
	{
		{
			s.Endpoints.SetFake()
		}
	}
	{
		{
			s.CreatedAt.SetFake()
		}
	}
	{
		{
			s.UpdatedAt.SetFake()
		}
	}
	{
		{
			s.Usage.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PatchedMetricsStorageAccessKey) SetFake() {
	{
		{
			s.ID.SetFake()
		}
	}
	{
		{
			s.UID.SetFake()
		}
	}
	{
		{
			s.Secret.SetFake()
		}
	}
	{
		{
			s.Token.SetFake()
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PatchedMetricsStorageEndpoints) SetFake() {
	{
		{
			s.Address = "string"
		}
	}
}

// SetFake set fake values.
func (s *PatchedMetricsStorageIcon) SetFake() {
	{
		{
			s.ID.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PatchedMetricsStorageUsage) SetFake() {
	{
		{
			s.MetricsRoutings = int(0)
		}
	}
	{
		{
			s.AlertRules = int(0)
		}
	}
	{
		{
			s.LogMeasureRules = int(0)
		}
	}
}

// SetFake set fake values.
func (s *PatchedNotificationRouting) SetFake() {
	{
		{
			s.UID.SetFake()
		}
	}
	{
		{
			s.ProjectID.SetFake()
		}
	}
	{
		{
			s.NotificationTarget.SetFake()
		}
	}
	{
		{
			s.NotificationTargetUID.SetFake()
		}
	}
	{
		{
			s.MatchLabels = nil
			for i := 0; i < 0; i++ {
				var elem MatchLabelsItem
				{
					elem.SetFake()
				}
				s.MatchLabels = append(s.MatchLabels, elem)
			}
		}
	}
	{
		{
			s.ResendIntervalMinutes.SetFake()
		}
	}
	{
		{
			s.Order.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PatchedNotificationTarget) SetFake() {
	{
		{
			s.UID.SetFake()
		}
	}
	{
		{
			s.ProjectID.SetFake()
		}
	}
	{
		{
			s.ServiceType.SetFake()
		}
	}
	{
		{
			s.URL.SetFake()
		}
	}
	{
		{ // Keep pointer nil to prevent infinite recursion.
			s.Config = nil
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PatchedNotificationTargetConfig) SetFake() {
}

// SetFake set fake values.
func (s *PatchedNotificationTargetServiceType) SetFake() {
	*s = PatchedNotificationTargetServiceTypeSAKURASIMPLENOTICE
}

// SetFake set fake values.
func (s *PatchedTraceStorage) SetFake() {
	{
		{
			s.ID.SetFake()
		}
	}
	{
		{
			s.Name.SetFake()
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.Tags = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.Tags = append(s.Tags, elem)
			}
		}
	}
	{
		{
			s.Icon.SetFake()
		}
	}
	{
		{
			s.RetentionPeriodDays.SetFake()
		}
	}
	{
		{
			s.CreatedAt.SetFake()
		}
	}
	{
		{
			s.Endpoints.SetFake()
		}
	}
	{
		{
			s.AccountID.SetFake()
		}
	}
	{
		{
			s.ResourceID.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PatchedTraceStorageAccessKey) SetFake() {
	{
		{
			s.UID.SetFake()
		}
	}
	{
		{
			s.Secret.SetFake()
		}
	}
	{
		{
			s.Token.SetFake()
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PatchedTraceStorageEndpoints) SetFake() {
	{
		{
			s.Ingester.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PatchedTraceStorageEndpointsIngester) SetFake() {
	{
		{
			s.Address = "string"
		}
	}
	{
		{
			s.Insecure.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PatchedTraceStorageIcon) SetFake() {
	{
		{
			s.ID.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PostProvisioningInitializeCreated) SetFake() {
	var unwrapped Provisioning
	{
		unwrapped.SetFake()
	}
	*s = PostProvisioningInitializeCreated(unwrapped)
}

// SetFake set fake values.
func (s *PostProvisioningInitializeOK) SetFake() {
	var unwrapped Provisioning
	{
		unwrapped.SetFake()
	}
	*s = PostProvisioningInitializeOK(unwrapped)
}

// SetFake set fake values.
func (s *Provisioning) SetFake() {
	{
		{
			s.Logs.SetFake()
		}
	}
	{
		{
			s.Metrics.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ProvisioningCreate) SetFake() {
	{
		{
			s.Logs.SetFake()
		}
	}
	{
		{
			s.Metrics.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ProvisioningExist) SetFake() {
	{
		{
			s.SystemExist = true
		}
	}
	{
		{
			s.UserExist = true
		}
	}
}

// SetFake set fake values.
func (s *Publisher) SetFake() {
	{
		{
			s.Code = "string"
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.Variants = nil
			for i := 0; i < 0; i++ {
				var elem PublisherVariant
				{
					elem.SetFake()
				}
				s.Variants = append(s.Variants, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *PublisherVariant) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Label = "string"
		}
	}
	{
		{
			s.Storage.SetFake()
		}
	}
	{
		{
			s.System.SetFake()
		}
	}
	{
		{
			s.MetricsPrefix.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PublisherVariantStorage) SetFake() {
	*s = PublisherVariantStorageMetrics
}

// SetFake set fake values.
func (s *PublisherVariantSystem) SetFake() {
	*s = PublisherVariantSystemDisallow
}

// SetFake set fake values.
func (s *ResourceItemLimits) SetFake() {
	{
		{
			s.MaxUserCount = int(0)
		}
	}
}

// SetFake set fake values.
func (s *ResourcesLimits) SetFake() {
	{
		{
			s.Logs.SetFake()
		}
	}
	{
		{
			s.Metrics.SetFake()
		}
	}
	{
		{
			s.Traces.SetFake()
		}
	}
	{
		{
			s.Alerts.SetFake()
		}
	}
	{
		{
			s.Dashboards.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *StrMatcher) SetFake() {
	{
		{
			s.Type.SetFake()
		}
	}
	{
		{
			s.Operator.SetFake()
		}
	}
	{
		{
			s.Field.SetFake()
		}
	}
	{
		{
			s.Value = "string"
		}
	}
	{
		{
			s.ValueList = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.ValueList = append(s.ValueList, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *StringFieldName) SetFake() {
	*s = StringFieldNameLogName
}

// SetFake set fake values.
func (s *TraceStorage) SetFake() {
	{
		{
			s.ID = int64(0)
		}
	}
	{
		{
			s.Name.SetFake()
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.Tags = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.Tags = append(s.Tags, elem)
			}
		}
	}
	{
		{
			s.Icon.SetFake()
		}
	}
	{
		{
			s.RetentionPeriodDays = int(0)
		}
	}
	{
		{
			s.CreatedAt = time.Now()
		}
	}
	{
		{
			s.Endpoints.SetFake()
		}
	}
	{
		{
			s.AccountID = "string"
		}
	}
	{
		{
			s.ResourceID = int64(0)
		}
	}
}

// SetFake set fake values.
func (s *TraceStorageAccessKey) SetFake() {
	{
		{
			s.UID = uuid.New()
		}
	}
	{
		{
			s.Secret = "string"
		}
	}
	{
		{
			s.Token = "string"
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *TraceStorageCreate) SetFake() {
	{
		{
			s.Classification.SetFake()
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *TraceStorageCreateClassification) SetFake() {
	*s = TraceStorageCreateClassificationShared
}

// SetFake set fake values.
func (s *TraceStorageEndpoints) SetFake() {
	{
		{
			s.Ingester.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *TraceStorageEndpointsIngester) SetFake() {
	{
		{
			s.Address = "string"
		}
	}
	{
		{
			s.Insecure.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *TraceStorageIcon) SetFake() {
	{
		{
			s.ID.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *Type) SetFake() {
	*s = TypeOr
}

// SetFake set fake values.
func (s *Type1) SetFake() {
	*s = Type1And
}

// SetFake set fake values.
func (s *Type2) SetFake() {
	*s = Type2String
}

// SetFake set fake values.
func (s *Type3) SetFake() {
	*s = Type3Number
}

// SetFake set fake values.
func (s *Type4) SetFake() {
	*s = Type4Enum
}

// SetFake set fake values.
func (s *Type5) SetFake() {
	*s = Type5MapKeyExists
}

// SetFake set fake values.
func (s *Type6) SetFake() {
	*s = Type6MapKeyValueMatcher
}

// SetFake set fake values.
func (s *ValueEnum) SetFake() {
	*s = ValueEnumDEFAULT
}

// SetFake set fake values.
func (s *WrappedAlertProject) SetFake() {
	{
		{
			s.ID = int64(0)
		}
	}
	{
		{
			s.Name.SetFake()
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.Tags = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.Tags = append(s.Tags, elem)
			}
		}
	}
	{
		{
			s.Icon.SetFake()
		}
	}
	{
		{
			s.AccountID = "string"
		}
	}
	{
		{
			s.ResourceID.SetFake()
		}
	}
	{
		{
			s.CreatedAt = time.Now()
		}
	}
	{
		{
			s.RulesURL = "string"
		}
	}
	{
		{
			s.NotificationTargetsURL = "string"
		}
	}
	{
		{
			s.NotificationRoutingsURL = "string"
		}
	}
	{
		{
			s.HistoriesURL = "string"
		}
	}
	{
		{
			s.LogMeasureRulesURL = "string"
		}
	}
	{
		{
			s.IsOk = true
		}
	}
}

// SetFake set fake values.
func (s *WrappedAlertProjectIcon) SetFake() {
	{
		{
			s.ID.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *WrappedDashboardProject) SetFake() {
	{
		{
			s.ID = int64(0)
		}
	}
	{
		{
			s.Name.SetFake()
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.Tags = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.Tags = append(s.Tags, elem)
			}
		}
	}
	{
		{
			s.Icon.SetFake()
		}
	}
	{
		{
			s.AccountID = "string"
		}
	}
	{
		{
			s.ResourceID.SetFake()
		}
	}
	{
		{
			s.CreatedAt = time.Now()
		}
	}
	{
		{
			s.IsOk = true
		}
	}
}

// SetFake set fake values.
func (s *WrappedDashboardProjectIcon) SetFake() {
	{
		{
			s.ID.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *WrappedLogRouting) SetFake() {
	{
		{
			s.ID = int64(0)
		}
	}
	{
		{
			s.UID = uuid.New()
		}
	}
	{
		{
			s.ResourceID.SetFake()
		}
	}
	{
		{
			s.Publisher.SetFake()
		}
	}
	{
		{
			s.PublisherCode.SetFake()
		}
	}
	{
		{
			s.Variant = "string"
		}
	}
	{
		{
			s.LogStorage.SetFake()
		}
	}
	{
		{
			s.LogStorageID.SetFake()
		}
	}
	{
		{
			s.CreatedAt = time.Now()
		}
	}
	{
		{
			s.UpdatedAt = time.Now()
		}
	}
	{
		{
			s.IsOk = true
		}
	}
}

// SetFake set fake values.
func (s *WrappedLogStorage) SetFake() {
	{
		{
			s.ID = int64(0)
		}
	}
	{
		{
			s.Name.SetFake()
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.Tags = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.Tags = append(s.Tags, elem)
			}
		}
	}
	{
		{
			s.Icon.SetFake()
		}
	}
	{
		{
			s.ExpireDay.SetFake()
		}
	}
	{
		{
			s.CreatedAt = time.Now()
		}
	}
	{
		{
			s.Endpoints.SetFake()
		}
	}
	{
		{
			s.AccountID = "string"
		}
	}
	{
		{
			s.ResourceID.SetFake()
		}
	}
	{
		{
			s.IsSystem = true
		}
	}
	{
		{
			s.Usage.SetFake()
		}
	}
	{
		{
			s.IsOk = true
		}
	}
}

// SetFake set fake values.
func (s *WrappedLogStorageAccessKey) SetFake() {
	{
		{
			s.ID = int64(0)
		}
	}
	{
		{
			s.UID = uuid.New()
		}
	}
	{
		{
			s.Secret = uuid.New()
		}
	}
	{
		{
			s.Token = "string"
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.IsOk = true
		}
	}
}

// SetFake set fake values.
func (s *WrappedLogStorageEndpoints) SetFake() {
	{
		{
			s.Ingester.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *WrappedLogStorageEndpointsIngester) SetFake() {
	{
		{
			s.Address = "string"
		}
	}
	{
		{
			s.Insecure.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *WrappedLogStorageIcon) SetFake() {
	{
		{
			s.ID.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *WrappedLogStorageUsage) SetFake() {
	{
		{
			s.LogRoutings = int(0)
		}
	}
	{
		{
			s.LogMeasureRules = int(0)
		}
	}
}

// SetFake set fake values.
func (s *WrappedMetricsRouting) SetFake() {
	{
		{
			s.ID = int64(0)
		}
	}
	{
		{
			s.UID = uuid.New()
		}
	}
	{
		{
			s.ResourceID.SetFake()
		}
	}
	{
		{
			s.Publisher.SetFake()
		}
	}
	{
		{
			s.PublisherCode.SetFake()
		}
	}
	{
		{
			s.Variant = "string"
		}
	}
	{
		{
			s.MetricsStorage.SetFake()
		}
	}
	{
		{
			s.MetricsStorageID.SetFake()
		}
	}
	{
		{
			s.CreatedAt = time.Now()
		}
	}
	{
		{
			s.UpdatedAt = time.Now()
		}
	}
	{
		{
			s.IsOk = true
		}
	}
}

// SetFake set fake values.
func (s *WrappedMetricsStorage) SetFake() {
	{
		{
			s.ID = int64(0)
		}
	}
	{
		{
			s.Name.SetFake()
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.Tags = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.Tags = append(s.Tags, elem)
			}
		}
	}
	{
		{
			s.Icon.SetFake()
		}
	}
	{
		{
			s.IsSystem = true
		}
	}
	{
		{
			s.AccountID = "string"
		}
	}
	{
		{
			s.ResourceID.SetFake()
		}
	}
	{
		{
			s.Endpoints.SetFake()
		}
	}
	{
		{
			s.CreatedAt = time.Now()
		}
	}
	{
		{
			s.UpdatedAt = time.Now()
		}
	}
	{
		{
			s.Usage.SetFake()
		}
	}
	{
		{
			s.IsOk = true
		}
	}
}

// SetFake set fake values.
func (s *WrappedMetricsStorageAccessKey) SetFake() {
	{
		{
			s.ID = int64(0)
		}
	}
	{
		{
			s.UID = uuid.New()
		}
	}
	{
		{
			s.Secret = uuid.New()
		}
	}
	{
		{
			s.Token = "string"
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.IsOk = true
		}
	}
}

// SetFake set fake values.
func (s *WrappedMetricsStorageEndpoints) SetFake() {
	{
		{
			s.Address = "string"
		}
	}
}

// SetFake set fake values.
func (s *WrappedMetricsStorageIcon) SetFake() {
	{
		{
			s.ID.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *WrappedMetricsStorageUsage) SetFake() {
	{
		{
			s.MetricsRoutings = int(0)
		}
	}
	{
		{
			s.AlertRules = int(0)
		}
	}
	{
		{
			s.LogMeasureRules = int(0)
		}
	}
}

// SetFake set fake values.
func (s *WrappedPublisher) SetFake() {
	{
		{
			s.Code = "string"
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.Variants = nil
			for i := 0; i < 0; i++ {
				var elem PublisherVariant
				{
					elem.SetFake()
				}
				s.Variants = append(s.Variants, elem)
			}
		}
	}
	{
		{
			s.IsOk = true
		}
	}
}

// SetFake set fake values.
func (s *WrappedTraceStorage) SetFake() {
	{
		{
			s.ID = int64(0)
		}
	}
	{
		{
			s.Name.SetFake()
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.Tags = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.Tags = append(s.Tags, elem)
			}
		}
	}
	{
		{
			s.Icon.SetFake()
		}
	}
	{
		{
			s.RetentionPeriodDays = int(0)
		}
	}
	{
		{
			s.CreatedAt = time.Now()
		}
	}
	{
		{
			s.Endpoints.SetFake()
		}
	}
	{
		{
			s.AccountID = "string"
		}
	}
	{
		{
			s.ResourceID = int64(0)
		}
	}
	{
		{
			s.IsOk = true
		}
	}
}

// SetFake set fake values.
func (s *WrappedTraceStorageAccessKey) SetFake() {
	{
		{
			s.UID = uuid.New()
		}
	}
	{
		{
			s.Secret = "string"
		}
	}
	{
		{
			s.Token = "string"
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.IsOk = true
		}
	}
}

// SetFake set fake values.
func (s *WrappedTraceStorageEndpoints) SetFake() {
	{
		{
			s.Ingester.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *WrappedTraceStorageEndpointsIngester) SetFake() {
	{
		{
			s.Address = "string"
		}
	}
	{
		{
			s.Insecure.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *WrappedTraceStorageIcon) SetFake() {
	{
		{
			s.ID.SetFake()
		}
	}
}
