// Code generated by ogen, DO NOT EDIT.

package v1

import (
	"context"
	"net/http"

	"github.com/go-faster/errors"
)

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// ProjectApiKeyAuth provides ProjectApiKeyAuth security value.
	// APIキー認証
	// - ユーザー名に発行したAPIキーのアクセストークンを指定
	// - パスワードに発行したAPIキーのアクセストークンシークレットを指定.
	ProjectApiKeyAuth(ctx context.Context, operationName OperationName) (ProjectApiKeyAuth, error)
	// ServicePrincipalAuth provides ServicePrincipalAuth security value.
	// サービスプリンシパル認証
	// - サービスプリンシパルのアクセストークンを指定.
	ServicePrincipalAuth(ctx context.Context, operationName OperationName) (ServicePrincipalAuth, error)
}

func (s *Client) securityProjectApiKeyAuth(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.ProjectApiKeyAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"ProjectApiKeyAuth\"")
	}
	req.SetBasicAuth(t.Username, t.Password)
	return nil
}
func (s *Client) securityServicePrincipalAuth(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.ServicePrincipalAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"ServicePrincipalAuth\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
