#====================
AUTHOR         ?= The sacloud/go-http authors
COPYRIGHT_YEAR ?= 2021-2025

SACLOUD_SDK_GO_ROOT := $(abspath $(dir $(lastword $(MAKEFILE_LIST)))/../..)
include $(SACLOUD_SDK_GO_ROOT)/makefiles/go/common.mk
#====================

default: $(DEFAULT_GOALS)
tools: dev-tools
