# Copyright 2026- The sacloud/sacloud-sdk-go Authors
# SPDX-License-Identifier: Apache-2.0

version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "00:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "ci:"
    cooldown:
      default-days: 7

  - package-ecosystem: gomod
    directories:
      - /
      - /api/apigw
      - /api/iaas/trace/otel
      - /api/webaccel
      - /service/iaas
      - /service/webaccel
    schedule:
      interval: daily
      time: "00:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "go:"
    cooldown:
      default-days: 7
