// Code generated by ogen, DO NOT EDIT.

package v1

// SetFake set fake values.
func (s *AvailabilityEnum) SetFake() {
	*s = AvailabilityEnumPrecreate
}

// SetFake set fake values.
func (s *CloudHSM) SetFake() {
	{
		{
			s.ID = "string"
		}
	}
	{
		{
			s.CreatedAt.SetFake()
		}
	}
	{
		{
			s.ModifiedAt.SetFake()
		}
	}
	{
		{
			s.ServiceClass.SetFake()
		}
	}
	{
		{
			s.Availability.SetFake()
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.Tags = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.Tags = append(s.Tags, elem)
			}
		}
	}
	{
		{
			s.Ipv4NetworkAddress = "string"
		}
	}
	{
		{
			s.Ipv4PrefixLength = int(0)
		}
	}
	{
		{
			s.Ipv4Address = "string"
		}
	}
	{
		{
			s.LocalRouter.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *CloudHSMClient) SetFake() {
	{
		{
			s.ID = "string"
		}
	}
	{
		{
			s.CreatedAt.SetFake()
		}
	}
	{
		{
			s.ModifiedAt.SetFake()
		}
	}
	{
		{
			s.Availability.SetFake()
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Certificate = "string"
		}
	}
}

// SetFake set fake values.
func (s *CloudHSMLocalRouter) SetFake() {
	{
		{
			s.ResourceID.SetFake()
		}
	}
	{
		{
			s.SecretKey.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *CloudHSMPeer) SetFake() {
	{
		{
			s.ID = "string"
		}
	}
	{
		{
			s.Index.SetFake()
		}
	}
	{
		{
			s.Status.SetFake()
		}
	}
	{
		{
			s.Routes = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.Routes = append(s.Routes, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *CloudHSMPeerList) SetFake() {
	{
		{
			s.Peers = nil
			for i := 0; i < 0; i++ {
				var elem CloudHSMPeer
				{
					elem.SetFake()
				}
				s.Peers = append(s.Peers, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *CloudHSMPeerStatus) SetFake() {
	*s = CloudHSMPeerStatusDOWN
}

// SetFake set fake values.
func (s *CloudHSMSoftwareLicense) SetFake() {
	{
		{
			s.ID = "string"
		}
	}
	{
		{
			s.CreatedAt.SetFake()
		}
	}
	{
		{
			s.ModifiedAt.SetFake()
		}
	}
	{
		{
			s.ServiceClass.SetFake()
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Description = "string"
		}
	}
	{
		{
			s.Tags = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.Tags = append(s.Tags, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *CloudHSMSoftwareLicenseServiceClassEnum) SetFake() {
	*s = CloudHSMSoftwareLicenseServiceClassEnumCloudCloudhsmLicenseL7
}

// SetFake set fake values.
func (s *CreateCloudHSM) SetFake() {
	{
		{
			s.ID = "string"
		}
	}
	{
		{
			s.CreatedAt.SetFake()
		}
	}
	{
		{
			s.ModifiedAt.SetFake()
		}
	}
	{
		{
			s.ServiceClass.SetFake()
		}
	}
	{
		{
			s.Availability.SetFake()
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.Tags = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.Tags = append(s.Tags, elem)
			}
		}
	}
	{
		{
			s.Ipv4NetworkAddress = "string"
		}
	}
	{
		{
			s.Ipv4PrefixLength = int(0)
		}
	}
	{
		{
			s.Ipv4Address = "string"
		}
	}
}

// SetFake set fake values.
func (s *CreateCloudHSMClient) SetFake() {
	{
		{
			s.ID = "string"
		}
	}
	{
		{
			s.CreatedAt.SetFake()
		}
	}
	{
		{
			s.ModifiedAt.SetFake()
		}
	}
	{
		{
			s.Availability.SetFake()
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Certificate = "string"
		}
	}
}

// SetFake set fake values.
func (s *CreateCloudHSMPeer) SetFake() {
	{
		{
			s.ID = "string"
		}
	}
	{
		{
			s.SecretKey = "string"
		}
	}
}

// SetFake set fake values.
func (s *CreateCloudHSMSoftwareLicense) SetFake() {
	{
		{
			s.ID = "string"
		}
	}
	{
		{
			s.CreatedAt.SetFake()
		}
	}
	{
		{
			s.ModifiedAt.SetFake()
		}
	}
	{
		{
			s.ServiceClass.SetFake()
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.Tags = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.Tags = append(s.Tags, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *DateTime) SetFake() {
	var unwrapped string
	{
		unwrapped = "string"
	}
	*s = DateTime(unwrapped)
}

// SetFake set fake values.
func (s *NilCloudHSMLocalRouter) SetFake() {
	s.Null = true
}

// SetFake set fake values.
func (s *OptCloudHSMPeerStatus) SetFake() {
	var elem CloudHSMPeerStatus
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptCloudHSMSoftwareLicense) SetFake() {
	var elem CloudHSMSoftwareLicense
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptCreateCloudHSMSoftwareLicense) SetFake() {
	var elem CreateCloudHSMSoftwareLicense
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptInt) SetFake() {
	var elem int
	{
		elem = int(0)
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptString) SetFake() {
	var elem string
	{
		elem = "string"
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *PaginatedCloudHSMClientList) SetFake() {
	{
		{
			s.Count = int(0)
		}
	}
	{
		{
			s.From.SetFake()
		}
	}
	{
		{
			s.Total.SetFake()
		}
	}
	{
		{
			s.Clients = nil
			for i := 0; i < 0; i++ {
				var elem CloudHSMClient
				{
					elem.SetFake()
				}
				s.Clients = append(s.Clients, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *PaginatedCloudHSMList) SetFake() {
	{
		{
			s.Count = int(0)
		}
	}
	{
		{
			s.From.SetFake()
		}
	}
	{
		{
			s.Total.SetFake()
		}
	}
	{
		{
			s.CloudHSMs = nil
			for i := 0; i < 0; i++ {
				var elem CloudHSM
				{
					elem.SetFake()
				}
				s.CloudHSMs = append(s.CloudHSMs, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *PaginatedCloudHSMSoftwareLicenseList) SetFake() {
	{
		{
			s.Count = int(0)
		}
	}
	{
		{
			s.From.SetFake()
		}
	}
	{
		{
			s.Total.SetFake()
		}
	}
	{
		{
			s.Licenses = nil
			for i := 0; i < 0; i++ {
				var elem CloudHSMSoftwareLicense
				{
					elem.SetFake()
				}
				s.Licenses = append(s.Licenses, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *ServiceClassEnum) SetFake() {
	*s = ServiceClassEnumCloudCloudhsmPartition
}

// SetFake set fake values.
func (s *WrappedCloudHSM) SetFake() {
	{
		{
			s.CloudHSM.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *WrappedCloudHSMClient) SetFake() {
	{
		{
			s.Client.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *WrappedCloudHSMSoftwareLicense) SetFake() {
	{
		{
			s.License.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *WrappedCreateCloudHSM) SetFake() {
	{
		{
			s.CloudHSM.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *WrappedCreateCloudHSMClient) SetFake() {
	{
		{
			s.Client.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *WrappedCreateCloudHSMPeer) SetFake() {
	{
		{
			s.Peer.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *WrappedCreateCloudHSMSoftwareLicense) SetFake() {
	{
		{
			s.License.SetFake()
		}
	}
}
