// Code generated by ogen, DO NOT EDIT.

package v1

// CreateCloudHSMClientParams is parameters of createCloudHSMClient operation.
type CreateCloudHSMClientParams struct {
	CloudhsmResourceID string
}

// CreateCloudHSMPeerParams is parameters of createCloudHSMPeer operation.
type CreateCloudHSMPeerParams struct {
	ResourceID string
}

// DeleteCloudHSMParams is parameters of deleteCloudHSM operation.
type DeleteCloudHSMParams struct {
	ResourceID string
}

// DeleteCloudHSMClientParams is parameters of deleteCloudHSMClient operation.
type DeleteCloudHSMClientParams struct {
	CloudhsmResourceID string
	// A unique value identifying this CloudHSMクライアント.
	ID string
}

// DeleteCloudHSMLicenseParams is parameters of deleteCloudHSMLicense operation.
type DeleteCloudHSMLicenseParams struct {
	ResourceID string
}

// DeleteCloudHSMPeerParams is parameters of deleteCloudHSMPeer operation.
type DeleteCloudHSMPeerParams struct {
	PeerID     string
	ResourceID string
}

// DownloadCloudHSMDocumentParams is parameters of downloadCloudHSMDocument operation.
type DownloadCloudHSMDocumentParams struct {
	// A unique value identifying this CloudHSMドキュメント.
	ID                string
	LicenseResourceID string
}

// ListCloudHSMClientsParams is parameters of listCloudHSMClients operation.
type ListCloudHSMClientsParams struct {
	// Number of results to return per page.
	Count OptInt `json:",omitempty,omitzero"`
	// The initial index from which to return the results.
	From               OptInt `json:",omitempty,omitzero"`
	CloudhsmResourceID string
}

// ListCloudHSMDocumentsParams is parameters of listCloudHSMDocuments operation.
type ListCloudHSMDocumentsParams struct {
	// Number of results to return per page.
	Count OptInt `json:",omitempty,omitzero"`
	// The initial index from which to return the results.
	From              OptInt `json:",omitempty,omitzero"`
	LicenseResourceID string
}

// ListCloudHSMLicensesParams is parameters of listCloudHSMLicenses operation.
type ListCloudHSMLicensesParams struct {
	// Number of results to return per page.
	Count OptInt `json:",omitempty,omitzero"`
	// The initial index from which to return the results.
	From OptInt `json:",omitempty,omitzero"`
}

// ListCloudHSMPeersParams is parameters of listCloudHSMPeers operation.
type ListCloudHSMPeersParams struct {
	ResourceID string
}

// ListCloudHSMsParams is parameters of listCloudHSMs operation.
type ListCloudHSMsParams struct {
	// Number of results to return per page.
	Count OptInt `json:",omitempty,omitzero"`
	// The initial index from which to return the results.
	From OptInt `json:",omitempty,omitzero"`
}

// ReadCloudHSMParams is parameters of readCloudHSM operation.
type ReadCloudHSMParams struct {
	ResourceID string
}

// ReadCloudHSMClientParams is parameters of readCloudHSMClient operation.
type ReadCloudHSMClientParams struct {
	CloudhsmResourceID string
	// A unique value identifying this CloudHSMクライアント.
	ID string
}

// ReadCloudHSMLicenseParams is parameters of readCloudHSMLicense operation.
type ReadCloudHSMLicenseParams struct {
	ResourceID string
}

// UpdateCloudHSMParams is parameters of updateCloudHSM operation.
type UpdateCloudHSMParams struct {
	ResourceID string
}

// UpdateCloudHSMClientParams is parameters of updateCloudHSMClient operation.
type UpdateCloudHSMClientParams struct {
	CloudhsmResourceID string
	// A unique value identifying this CloudHSMクライアント.
	ID string
}

// UpdateCloudHSMLicenseParams is parameters of updateCloudHSMLicense operation.
type UpdateCloudHSMLicenseParams struct {
	ResourceID string
}
