// Code generated by ogen, DO NOT EDIT.

package v1

import (
	"net/url"
	"time"

	"github.com/go-faster/jx"
)

// Ref: #/components/schemas/AiRequestBody
type AiRequestBody struct {
	Location string       `json:"location"`
	Sku      AiServiceSku `json:"sku"`
}

// GetLocation returns the value of Location.
func (s *AiRequestBody) GetLocation() string {
	return s.Location
}

// GetSku returns the value of Sku.
func (s *AiRequestBody) GetSku() AiServiceSku {
	return s.Sku
}

// SetLocation sets the value of Location.
func (s *AiRequestBody) SetLocation(val string) {
	s.Location = val
}

// SetSku sets the value of Sku.
func (s *AiRequestBody) SetSku(val AiServiceSku) {
	s.Sku = val
}

// Ref: #/components/schemas/AiServiceSku
type AiServiceSku int32

const (
	AiServiceSku1 AiServiceSku = 1
)

// AllValues returns all AiServiceSku values.
func (AiServiceSku) AllValues() []AiServiceSku {
	return []AiServiceSku{
		AiServiceSku1,
	}
}

// Ref: #/components/schemas/AzureLocation
type AzureLocation struct {
	Name        OptNilString `json:"name"`
	DisplayName OptNilString `json:"displayName"`
}

// GetName returns the value of Name.
func (s *AzureLocation) GetName() OptNilString {
	return s.Name
}

// GetDisplayName returns the value of DisplayName.
func (s *AzureLocation) GetDisplayName() OptNilString {
	return s.DisplayName
}

// SetName sets the value of Name.
func (s *AzureLocation) SetName(val OptNilString) {
	s.Name = val
}

// SetDisplayName sets the value of DisplayName.
func (s *AzureLocation) SetDisplayName(val OptNilString) {
	s.DisplayName = val
}

// Ref: #/components/schemas/CreatedByType
type CreatedByType struct{}

// Ref: #/components/schemas/DataLakePerformance
type DataLakePerformance int32

const (
	DataLakePerformance1 DataLakePerformance = 1
	DataLakePerformance2 DataLakePerformance = 2
)

// AllValues returns all DataLakePerformance values.
func (DataLakePerformance) AllValues() []DataLakePerformance {
	return []DataLakePerformance{
		DataLakePerformance1,
		DataLakePerformance2,
	}
}

// Ref: #/components/schemas/DataLakeRedundancy
type DataLakeRedundancy int32

const (
	DataLakeRedundancy1 DataLakeRedundancy = 1
	DataLakeRedundancy2 DataLakeRedundancy = 2
	DataLakeRedundancy3 DataLakeRedundancy = 3
	DataLakeRedundancy4 DataLakeRedundancy = 4
)

// AllValues returns all DataLakeRedundancy values.
func (DataLakeRedundancy) AllValues() []DataLakeRedundancy {
	return []DataLakeRedundancy{
		DataLakeRedundancy1,
		DataLakeRedundancy2,
		DataLakeRedundancy3,
		DataLakeRedundancy4,
	}
}

// Ref: #/components/schemas/DatalakePostRequestBody
type DatalakePostRequestBody struct {
	Location    string              `json:"location"`
	Performance DataLakePerformance `json:"performance"`
	Redundancy  DataLakeRedundancy  `json:"redundancy"`
	AccountType OptNilString        `json:"accountType"`
}

// GetLocation returns the value of Location.
func (s *DatalakePostRequestBody) GetLocation() string {
	return s.Location
}

// GetPerformance returns the value of Performance.
func (s *DatalakePostRequestBody) GetPerformance() DataLakePerformance {
	return s.Performance
}

// GetRedundancy returns the value of Redundancy.
func (s *DatalakePostRequestBody) GetRedundancy() DataLakeRedundancy {
	return s.Redundancy
}

// GetAccountType returns the value of AccountType.
func (s *DatalakePostRequestBody) GetAccountType() OptNilString {
	return s.AccountType
}

// SetLocation sets the value of Location.
func (s *DatalakePostRequestBody) SetLocation(val string) {
	s.Location = val
}

// SetPerformance sets the value of Performance.
func (s *DatalakePostRequestBody) SetPerformance(val DataLakePerformance) {
	s.Performance = val
}

// SetRedundancy sets the value of Redundancy.
func (s *DatalakePostRequestBody) SetRedundancy(val DataLakeRedundancy) {
	s.Redundancy = val
}

// SetAccountType sets the value of AccountType.
func (s *DatalakePostRequestBody) SetAccountType(val OptNilString) {
	s.AccountType = val
}

// Ref: #/components/schemas/DatawarehousePostRequestBody
type DatawarehousePostRequestBody struct {
	Location string `json:"location"`
}

// GetLocation returns the value of Location.
func (s *DatawarehousePostRequestBody) GetLocation() string {
	return s.Location
}

// SetLocation sets the value of Location.
func (s *DatawarehousePostRequestBody) SetLocation(val string) {
	s.Location = val
}

// Ref: #/components/schemas/DdosRequestBody
type DdosRequestBody struct {
	Location string            `json:"location"`
	Profile  FrontDoorProfile  `json:"profile"`
	Endpoint FrontDoorEndpoint `json:"endpoint"`
}

// GetLocation returns the value of Location.
func (s *DdosRequestBody) GetLocation() string {
	return s.Location
}

// GetProfile returns the value of Profile.
func (s *DdosRequestBody) GetProfile() FrontDoorProfile {
	return s.Profile
}

// GetEndpoint returns the value of Endpoint.
func (s *DdosRequestBody) GetEndpoint() FrontDoorEndpoint {
	return s.Endpoint
}

// SetLocation sets the value of Location.
func (s *DdosRequestBody) SetLocation(val string) {
	s.Location = val
}

// SetProfile sets the value of Profile.
func (s *DdosRequestBody) SetProfile(val FrontDoorProfile) {
	s.Profile = val
}

// SetEndpoint sets the value of Endpoint.
func (s *DdosRequestBody) SetEndpoint(val FrontDoorEndpoint) {
	s.Endpoint = val
}

// DeleteAZ0101NoContent is response for DeleteAZ0101 operation.
type DeleteAZ0101NoContent struct{}

func (*DeleteAZ0101NoContent) deleteAZ0101Res() {}

// DeleteAZ0101NotFound is response for DeleteAZ0101 operation.
type DeleteAZ0101NotFound struct{}

func (*DeleteAZ0101NotFound) deleteAZ0101Res() {}

// DeleteAZ0102NoContent is response for DeleteAZ0102 operation.
type DeleteAZ0102NoContent struct{}

func (*DeleteAZ0102NoContent) deleteAZ0102Res() {}

// DeleteAZ0102NotFound is response for DeleteAZ0102 operation.
type DeleteAZ0102NotFound struct{}

func (*DeleteAZ0102NotFound) deleteAZ0102Res() {}

// DeleteAZ0103NoContent is response for DeleteAZ0103 operation.
type DeleteAZ0103NoContent struct{}

func (*DeleteAZ0103NoContent) deleteAZ0103Res() {}

// DeleteAZ0103NotFound is response for DeleteAZ0103 operation.
type DeleteAZ0103NotFound struct{}

func (*DeleteAZ0103NotFound) deleteAZ0103Res() {}

// DeleteAZ0104NoContent is response for DeleteAZ0104 operation.
type DeleteAZ0104NoContent struct{}

func (*DeleteAZ0104NoContent) deleteAZ0104Res() {}

// DeleteAZ0104NotFound is response for DeleteAZ0104 operation.
type DeleteAZ0104NotFound struct{}

func (*DeleteAZ0104NotFound) deleteAZ0104Res() {}

// DeleteAZ0105NoContent is response for DeleteAZ0105 operation.
type DeleteAZ0105NoContent struct{}

func (*DeleteAZ0105NoContent) deleteAZ0105Res() {}

// DeleteAZ0105NotFound is response for DeleteAZ0105 operation.
type DeleteAZ0105NotFound struct{}

func (*DeleteAZ0105NotFound) deleteAZ0105Res() {}

// DeleteAZ0107NoContent is response for DeleteAZ0107 operation.
type DeleteAZ0107NoContent struct{}

func (*DeleteAZ0107NoContent) deleteAZ0107Res() {}

// DeleteAZ0107NotFound is response for DeleteAZ0107 operation.
type DeleteAZ0107NotFound struct{}

func (*DeleteAZ0107NotFound) deleteAZ0107Res() {}

// DeleteAZ0301NoContent is response for DeleteAZ0301 operation.
type DeleteAZ0301NoContent struct{}

func (*DeleteAZ0301NoContent) deleteAZ0301Res() {}

// DeleteAZ0301NotFound is response for DeleteAZ0301 operation.
type DeleteAZ0301NotFound struct{}

func (*DeleteAZ0301NotFound) deleteAZ0301Res() {}

// DeleteAZ0401NoContent is response for DeleteAZ0401 operation.
type DeleteAZ0401NoContent struct{}

func (*DeleteAZ0401NoContent) deleteAZ0401Res() {}

// DeleteAZ0401NotFound is response for DeleteAZ0401 operation.
type DeleteAZ0401NotFound struct{}

func (*DeleteAZ0401NotFound) deleteAZ0401Res() {}

// DeleteAZ0402NoContent is response for DeleteAZ0402 operation.
type DeleteAZ0402NoContent struct{}

func (*DeleteAZ0402NoContent) deleteAZ0402Res() {}

// DeleteAZ0402NotFound is response for DeleteAZ0402 operation.
type DeleteAZ0402NotFound struct{}

func (*DeleteAZ0402NotFound) deleteAZ0402Res() {}

// DeleteAZ0403NoContent is response for DeleteAZ0403 operation.
type DeleteAZ0403NoContent struct{}

func (*DeleteAZ0403NoContent) deleteAZ0403Res() {}

// DeleteAZ0403NotFound is response for DeleteAZ0403 operation.
type DeleteAZ0403NotFound struct{}

func (*DeleteAZ0403NotFound) deleteAZ0403Res() {}

// DeleteAZ0501NoContent is response for DeleteAZ0501 operation.
type DeleteAZ0501NoContent struct{}

func (*DeleteAZ0501NoContent) deleteAZ0501Res() {}

// DeleteAZ0501NotFound is response for DeleteAZ0501 operation.
type DeleteAZ0501NotFound struct{}

func (*DeleteAZ0501NotFound) deleteAZ0501Res() {}

// Ref: #/components/schemas/DeploymentStatus
type DeploymentStatus struct {
	ID         OptNilString                  `json:"id"`
	Name       OptNilString                  `json:"name"`
	Type       OptNilString                  `json:"type"`
	Properties OptDeploymentStatusProperties `json:"properties"`
}

// GetID returns the value of ID.
func (s *DeploymentStatus) GetID() OptNilString {
	return s.ID
}

// GetName returns the value of Name.
func (s *DeploymentStatus) GetName() OptNilString {
	return s.Name
}

// GetType returns the value of Type.
func (s *DeploymentStatus) GetType() OptNilString {
	return s.Type
}

// GetProperties returns the value of Properties.
func (s *DeploymentStatus) GetProperties() OptDeploymentStatusProperties {
	return s.Properties
}

// SetID sets the value of ID.
func (s *DeploymentStatus) SetID(val OptNilString) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *DeploymentStatus) SetName(val OptNilString) {
	s.Name = val
}

// SetType sets the value of Type.
func (s *DeploymentStatus) SetType(val OptNilString) {
	s.Type = val
}

// SetProperties sets the value of Properties.
func (s *DeploymentStatus) SetProperties(val OptDeploymentStatusProperties) {
	s.Properties = val
}

func (*DeploymentStatus) statusAZ0101Res() {}
func (*DeploymentStatus) statusAZ0102Res() {}
func (*DeploymentStatus) statusAZ0103Res() {}
func (*DeploymentStatus) statusAZ0104Res() {}
func (*DeploymentStatus) statusAZ0105Res() {}
func (*DeploymentStatus) statusAZ0107Res() {}
func (*DeploymentStatus) statusAZ0301Res() {}
func (*DeploymentStatus) statusAZ0401Res() {}
func (*DeploymentStatus) statusAZ0402Res() {}
func (*DeploymentStatus) statusAZ0501Res() {}

// Ref: #/components/schemas/DeploymentStatusProperties
type DeploymentStatusProperties struct {
	ProvisioningState OptNilString `json:"provisioningState"`
	Timestamp         OptDateTime  `json:"timestamp"`
}

// GetProvisioningState returns the value of ProvisioningState.
func (s *DeploymentStatusProperties) GetProvisioningState() OptNilString {
	return s.ProvisioningState
}

// GetTimestamp returns the value of Timestamp.
func (s *DeploymentStatusProperties) GetTimestamp() OptDateTime {
	return s.Timestamp
}

// SetProvisioningState sets the value of ProvisioningState.
func (s *DeploymentStatusProperties) SetProvisioningState(val OptNilString) {
	s.ProvisioningState = val
}

// SetTimestamp sets the value of Timestamp.
func (s *DeploymentStatusProperties) SetTimestamp(val OptDateTime) {
	s.Timestamp = val
}

// Ref: #/components/schemas/ErrorInfo
type ErrorInfo struct {
	Code    OptNilString `json:"code"`
	Message OptNilString `json:"message"`
}

// GetCode returns the value of Code.
func (s *ErrorInfo) GetCode() OptNilString {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ErrorInfo) GetMessage() OptNilString {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ErrorInfo) SetCode(val OptNilString) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ErrorInfo) SetMessage(val OptNilString) {
	s.Message = val
}

// Ref: #/components/schemas/ErrorResponse
type ErrorResponse struct {
	Errors OptNilErrorInfoArray `json:"errors"`
}

// GetErrors returns the value of Errors.
func (s *ErrorResponse) GetErrors() OptNilErrorInfoArray {
	return s.Errors
}

// SetErrors sets the value of Errors.
func (s *ErrorResponse) SetErrors(val OptNilErrorInfoArray) {
	s.Errors = val
}

func (*ErrorResponse) createAZ0101Res() {}
func (*ErrorResponse) createAZ0102Res() {}
func (*ErrorResponse) createAZ0103Res() {}
func (*ErrorResponse) createAZ0104Res() {}
func (*ErrorResponse) createAZ0105Res() {}
func (*ErrorResponse) createAZ0107Res() {}
func (*ErrorResponse) createAZ0301Res() {}
func (*ErrorResponse) createAZ0401Res() {}
func (*ErrorResponse) createAZ0402Res() {}
func (*ErrorResponse) createAZ0403Res() {}
func (*ErrorResponse) createAZ0501Res() {}
func (*ErrorResponse) deleteAZ0101Res() {}
func (*ErrorResponse) deleteAZ0102Res() {}
func (*ErrorResponse) deleteAZ0103Res() {}
func (*ErrorResponse) deleteAZ0104Res() {}
func (*ErrorResponse) deleteAZ0105Res() {}
func (*ErrorResponse) deleteAZ0107Res() {}
func (*ErrorResponse) deleteAZ0301Res() {}
func (*ErrorResponse) deleteAZ0401Res() {}
func (*ErrorResponse) deleteAZ0402Res() {}
func (*ErrorResponse) deleteAZ0403Res() {}
func (*ErrorResponse) deleteAZ0501Res() {}
func (*ErrorResponse) getAZ0101Res()    {}
func (*ErrorResponse) getAZ0102Res()    {}
func (*ErrorResponse) getAZ0103Res()    {}
func (*ErrorResponse) getAZ0104Res()    {}
func (*ErrorResponse) getAZ0105Res()    {}
func (*ErrorResponse) getAZ0107Res()    {}
func (*ErrorResponse) getAZ0301Res()    {}
func (*ErrorResponse) getAZ0401Res()    {}
func (*ErrorResponse) getAZ0402Res()    {}
func (*ErrorResponse) getAZ0403Res()    {}
func (*ErrorResponse) getAZ0501Res()    {}
func (*ErrorResponse) listAZ0101Res()   {}
func (*ErrorResponse) listAZ0102Res()   {}
func (*ErrorResponse) listAZ0103Res()   {}
func (*ErrorResponse) listAZ0104Res()   {}
func (*ErrorResponse) listAZ0105Res()   {}
func (*ErrorResponse) listAZ0107Res()   {}
func (*ErrorResponse) listAZ0301Res()   {}
func (*ErrorResponse) listAZ0401Res()   {}
func (*ErrorResponse) listAZ0402Res()   {}
func (*ErrorResponse) listAZ0403Res()   {}
func (*ErrorResponse) listAZ0501Res()   {}
func (*ErrorResponse) statusAZ0101Res() {}
func (*ErrorResponse) statusAZ0102Res() {}
func (*ErrorResponse) statusAZ0103Res() {}
func (*ErrorResponse) statusAZ0104Res() {}
func (*ErrorResponse) statusAZ0105Res() {}
func (*ErrorResponse) statusAZ0107Res() {}
func (*ErrorResponse) statusAZ0301Res() {}
func (*ErrorResponse) statusAZ0401Res() {}
func (*ErrorResponse) statusAZ0402Res() {}
func (*ErrorResponse) statusAZ0501Res() {}

// Ref: #/components/schemas/EtlPostRequestBody
type EtlPostRequestBody struct {
	Location string `json:"location"`
}

// GetLocation returns the value of Location.
func (s *EtlPostRequestBody) GetLocation() string {
	return s.Location
}

// SetLocation sets the value of Location.
func (s *EtlPostRequestBody) SetLocation(val string) {
	s.Location = val
}

// Ref: #/components/schemas/FrontDoorEndpoint
type FrontDoorEndpoint struct {
	Route FrontDoorRoute `json:"route"`
}

// GetRoute returns the value of Route.
func (s *FrontDoorEndpoint) GetRoute() FrontDoorRoute {
	return s.Route
}

// SetRoute sets the value of Route.
func (s *FrontDoorEndpoint) SetRoute(val FrontDoorRoute) {
	s.Route = val
}

// Ref: #/components/schemas/FrontDoorOrigin
type FrontDoorOrigin struct {
	HostName   string `json:"hostName"`
	HostHeader string `json:"hostHeader"`
}

// GetHostName returns the value of HostName.
func (s *FrontDoorOrigin) GetHostName() string {
	return s.HostName
}

// GetHostHeader returns the value of HostHeader.
func (s *FrontDoorOrigin) GetHostHeader() string {
	return s.HostHeader
}

// SetHostName sets the value of HostName.
func (s *FrontDoorOrigin) SetHostName(val string) {
	s.HostName = val
}

// SetHostHeader sets the value of HostHeader.
func (s *FrontDoorOrigin) SetHostHeader(val string) {
	s.HostHeader = val
}

// Ref: #/components/schemas/FrontDoorOriginGroup
type FrontDoorOriginGroup struct {
	Origin FrontDoorOrigin `json:"origin"`
}

// GetOrigin returns the value of Origin.
func (s *FrontDoorOriginGroup) GetOrigin() FrontDoorOrigin {
	return s.Origin
}

// SetOrigin sets the value of Origin.
func (s *FrontDoorOriginGroup) SetOrigin(val FrontDoorOrigin) {
	s.Origin = val
}

// Ref: #/components/schemas/FrontDoorProfile
type FrontDoorProfile struct {
	Level                     PricingLevel `json:"level"`
	LevelNameOfBicepParameter OptNilString `json:"levelNameOfBicepParameter"`
}

// GetLevel returns the value of Level.
func (s *FrontDoorProfile) GetLevel() PricingLevel {
	return s.Level
}

// GetLevelNameOfBicepParameter returns the value of LevelNameOfBicepParameter.
func (s *FrontDoorProfile) GetLevelNameOfBicepParameter() OptNilString {
	return s.LevelNameOfBicepParameter
}

// SetLevel sets the value of Level.
func (s *FrontDoorProfile) SetLevel(val PricingLevel) {
	s.Level = val
}

// SetLevelNameOfBicepParameter sets the value of LevelNameOfBicepParameter.
func (s *FrontDoorProfile) SetLevelNameOfBicepParameter(val OptNilString) {
	s.LevelNameOfBicepParameter = val
}

// Ref: #/components/schemas/FrontDoorRoute
type FrontDoorRoute struct {
	Patterns    []string             `json:"patterns"`
	OriginGroup FrontDoorOriginGroup `json:"originGroup"`
}

// GetPatterns returns the value of Patterns.
func (s *FrontDoorRoute) GetPatterns() []string {
	return s.Patterns
}

// GetOriginGroup returns the value of OriginGroup.
func (s *FrontDoorRoute) GetOriginGroup() FrontDoorOriginGroup {
	return s.OriginGroup
}

// SetPatterns sets the value of Patterns.
func (s *FrontDoorRoute) SetPatterns(val []string) {
	s.Patterns = val
}

// SetOriginGroup sets the value of OriginGroup.
func (s *FrontDoorRoute) SetOriginGroup(val FrontDoorOriginGroup) {
	s.OriginGroup = val
}

// GetAZ0101NotFound is response for GetAZ0101 operation.
type GetAZ0101NotFound struct{}

func (*GetAZ0101NotFound) getAZ0101Res() {}

// GetAZ0102NotFound is response for GetAZ0102 operation.
type GetAZ0102NotFound struct{}

func (*GetAZ0102NotFound) getAZ0102Res() {}

// GetAZ0103NotFound is response for GetAZ0103 operation.
type GetAZ0103NotFound struct{}

func (*GetAZ0103NotFound) getAZ0103Res() {}

// GetAZ0104NotFound is response for GetAZ0104 operation.
type GetAZ0104NotFound struct{}

func (*GetAZ0104NotFound) getAZ0104Res() {}

// GetAZ0105NotFound is response for GetAZ0105 operation.
type GetAZ0105NotFound struct{}

func (*GetAZ0105NotFound) getAZ0105Res() {}

// GetAZ0107NotFound is response for GetAZ0107 operation.
type GetAZ0107NotFound struct{}

func (*GetAZ0107NotFound) getAZ0107Res() {}

// GetAZ0301NotFound is response for GetAZ0301 operation.
type GetAZ0301NotFound struct{}

func (*GetAZ0301NotFound) getAZ0301Res() {}

// GetAZ0401NotFound is response for GetAZ0401 operation.
type GetAZ0401NotFound struct{}

func (*GetAZ0401NotFound) getAZ0401Res() {}

// GetAZ0402NotFound is response for GetAZ0402 operation.
type GetAZ0402NotFound struct{}

func (*GetAZ0402NotFound) getAZ0402Res() {}

// GetAZ0403NotFound is response for GetAZ0403 operation.
type GetAZ0403NotFound struct{}

func (*GetAZ0403NotFound) getAZ0403Res() {}

// GetAZ0501NotFound is response for GetAZ0501 operation.
type GetAZ0501NotFound struct{}

func (*GetAZ0501NotFound) getAZ0501Res() {}

// Ref: #/components/schemas/GetResourceResponse
type GetResourceResponse struct {
	Data jx.Raw       `json:"data"`
	URL  OptNilString `json:"url"`
}

// GetData returns the value of Data.
func (s *GetResourceResponse) GetData() jx.Raw {
	return s.Data
}

// GetURL returns the value of URL.
func (s *GetResourceResponse) GetURL() OptNilString {
	return s.URL
}

// SetData sets the value of Data.
func (s *GetResourceResponse) SetData(val jx.Raw) {
	s.Data = val
}

// SetURL sets the value of URL.
func (s *GetResourceResponse) SetURL(val OptNilString) {
	s.URL = val
}

func (*GetResourceResponse) getAZ0101Res() {}
func (*GetResourceResponse) getAZ0102Res() {}
func (*GetResourceResponse) getAZ0103Res() {}
func (*GetResourceResponse) getAZ0104Res() {}
func (*GetResourceResponse) getAZ0105Res() {}
func (*GetResourceResponse) getAZ0107Res() {}
func (*GetResourceResponse) getAZ0301Res() {}
func (*GetResourceResponse) getAZ0401Res() {}
func (*GetResourceResponse) getAZ0402Res() {}
func (*GetResourceResponse) getAZ0403Res() {}
func (*GetResourceResponse) getAZ0501Res() {}

// ListAZ0101NotFound is response for ListAZ0101 operation.
type ListAZ0101NotFound struct{}

func (*ListAZ0101NotFound) listAZ0101Res() {}

// ListAZ0102NotFound is response for ListAZ0102 operation.
type ListAZ0102NotFound struct{}

func (*ListAZ0102NotFound) listAZ0102Res() {}

// ListAZ0103NotFound is response for ListAZ0103 operation.
type ListAZ0103NotFound struct{}

func (*ListAZ0103NotFound) listAZ0103Res() {}

// ListAZ0104NotFound is response for ListAZ0104 operation.
type ListAZ0104NotFound struct{}

func (*ListAZ0104NotFound) listAZ0104Res() {}

// ListAZ0105NotFound is response for ListAZ0105 operation.
type ListAZ0105NotFound struct{}

func (*ListAZ0105NotFound) listAZ0105Res() {}

// ListAZ0107NotFound is response for ListAZ0107 operation.
type ListAZ0107NotFound struct{}

func (*ListAZ0107NotFound) listAZ0107Res() {}

// ListAZ0301NotFound is response for ListAZ0301 operation.
type ListAZ0301NotFound struct{}

func (*ListAZ0301NotFound) listAZ0301Res() {}

// ListAZ0401NotFound is response for ListAZ0401 operation.
type ListAZ0401NotFound struct{}

func (*ListAZ0401NotFound) listAZ0401Res() {}

// ListAZ0402NotFound is response for ListAZ0402 operation.
type ListAZ0402NotFound struct{}

func (*ListAZ0402NotFound) listAZ0402Res() {}

// ListAZ0403NotFound is response for ListAZ0403 operation.
type ListAZ0403NotFound struct{}

func (*ListAZ0403NotFound) listAZ0403Res() {}

// ListAZ0501NotFound is response for ListAZ0501 operation.
type ListAZ0501NotFound struct{}

func (*ListAZ0501NotFound) listAZ0501Res() {}

// Ref: #/components/schemas/ListResourcesResponse
type ListResourcesResponse struct {
	Resources OptNilResourceGroupResourceArray `json:"resources"`
}

// GetResources returns the value of Resources.
func (s *ListResourcesResponse) GetResources() OptNilResourceGroupResourceArray {
	return s.Resources
}

// SetResources sets the value of Resources.
func (s *ListResourcesResponse) SetResources(val OptNilResourceGroupResourceArray) {
	s.Resources = val
}

func (*ListResourcesResponse) listAZ0101Res() {}
func (*ListResourcesResponse) listAZ0102Res() {}
func (*ListResourcesResponse) listAZ0103Res() {}
func (*ListResourcesResponse) listAZ0104Res() {}
func (*ListResourcesResponse) listAZ0105Res() {}
func (*ListResourcesResponse) listAZ0107Res() {}
func (*ListResourcesResponse) listAZ0301Res() {}
func (*ListResourcesResponse) listAZ0401Res() {}
func (*ListResourcesResponse) listAZ0402Res() {}
func (*ListResourcesResponse) listAZ0403Res() {}
func (*ListResourcesResponse) listAZ0501Res() {}

// Ref: #/components/schemas/NetworkRequestBody
type NetworkRequestBody struct {
	Location string            `json:"location"`
	Profile  FrontDoorProfile  `json:"profile"`
	Endpoint FrontDoorEndpoint `json:"endpoint"`
}

// GetLocation returns the value of Location.
func (s *NetworkRequestBody) GetLocation() string {
	return s.Location
}

// GetProfile returns the value of Profile.
func (s *NetworkRequestBody) GetProfile() FrontDoorProfile {
	return s.Profile
}

// GetEndpoint returns the value of Endpoint.
func (s *NetworkRequestBody) GetEndpoint() FrontDoorEndpoint {
	return s.Endpoint
}

// SetLocation sets the value of Location.
func (s *NetworkRequestBody) SetLocation(val string) {
	s.Location = val
}

// SetProfile sets the value of Profile.
func (s *NetworkRequestBody) SetProfile(val FrontDoorProfile) {
	s.Profile = val
}

// SetEndpoint sets the value of Endpoint.
func (s *NetworkRequestBody) SetEndpoint(val FrontDoorEndpoint) {
	s.Endpoint = val
}

// NewNilString returns new NilString with value set to v.
func NewNilString(v string) NilString {
	return NilString{
		Value: v,
	}
}

// NilString is nullable string.
type NilString struct {
	Value string
	Null  bool
}

// SetTo sets value to v.
func (o *NilString) SetTo(v string) {
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o NilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *NilString) SetToNull() {
	o.Null = true
	var v string
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o NilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o NilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptAzureLocation returns new OptAzureLocation with value set to v.
func NewOptAzureLocation(v AzureLocation) OptAzureLocation {
	return OptAzureLocation{
		Value: v,
		Set:   true,
	}
}

// OptAzureLocation is optional AzureLocation.
type OptAzureLocation struct {
	Value AzureLocation
	Set   bool
}

// IsSet returns true if OptAzureLocation was set.
func (o OptAzureLocation) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptAzureLocation) Reset() {
	var v AzureLocation
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptAzureLocation) SetTo(v AzureLocation) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptAzureLocation) Get() (v AzureLocation, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptAzureLocation) Or(d AzureLocation) AzureLocation {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDeploymentStatusProperties returns new OptDeploymentStatusProperties with value set to v.
func NewOptDeploymentStatusProperties(v DeploymentStatusProperties) OptDeploymentStatusProperties {
	return OptDeploymentStatusProperties{
		Value: v,
		Set:   true,
	}
}

// OptDeploymentStatusProperties is optional DeploymentStatusProperties.
type OptDeploymentStatusProperties struct {
	Value DeploymentStatusProperties
	Set   bool
}

// IsSet returns true if OptDeploymentStatusProperties was set.
func (o OptDeploymentStatusProperties) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDeploymentStatusProperties) Reset() {
	var v DeploymentStatusProperties
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDeploymentStatusProperties) SetTo(v DeploymentStatusProperties) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDeploymentStatusProperties) Get() (v DeploymentStatusProperties, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDeploymentStatusProperties) Or(d DeploymentStatusProperties) DeploymentStatusProperties {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilDateTime returns new OptNilDateTime with value set to v.
func NewOptNilDateTime(v time.Time) OptNilDateTime {
	return OptNilDateTime{
		Value: v,
		Set:   true,
	}
}

// OptNilDateTime is optional nullable time.Time.
type OptNilDateTime struct {
	Value time.Time
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilDateTime was set.
func (o OptNilDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilDateTime) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilDateTime) SetToNull() {
	o.Set = true
	o.Null = true
	var v time.Time
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilDateTime) Get() (v time.Time, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilErrorInfoArray returns new OptNilErrorInfoArray with value set to v.
func NewOptNilErrorInfoArray(v []ErrorInfo) OptNilErrorInfoArray {
	return OptNilErrorInfoArray{
		Value: v,
		Set:   true,
	}
}

// OptNilErrorInfoArray is optional nullable []ErrorInfo.
type OptNilErrorInfoArray struct {
	Value []ErrorInfo
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilErrorInfoArray was set.
func (o OptNilErrorInfoArray) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilErrorInfoArray) Reset() {
	var v []ErrorInfo
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilErrorInfoArray) SetTo(v []ErrorInfo) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilErrorInfoArray) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilErrorInfoArray) SetToNull() {
	o.Set = true
	o.Null = true
	var v []ErrorInfo
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilErrorInfoArray) Get() (v []ErrorInfo, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilErrorInfoArray) Or(d []ErrorInfo) []ErrorInfo {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilResourceGroupDataTags returns new OptNilResourceGroupDataTags with value set to v.
func NewOptNilResourceGroupDataTags(v ResourceGroupDataTags) OptNilResourceGroupDataTags {
	return OptNilResourceGroupDataTags{
		Value: v,
		Set:   true,
	}
}

// OptNilResourceGroupDataTags is optional nullable ResourceGroupDataTags.
type OptNilResourceGroupDataTags struct {
	Value ResourceGroupDataTags
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilResourceGroupDataTags was set.
func (o OptNilResourceGroupDataTags) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilResourceGroupDataTags) Reset() {
	var v ResourceGroupDataTags
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilResourceGroupDataTags) SetTo(v ResourceGroupDataTags) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilResourceGroupDataTags) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilResourceGroupDataTags) SetToNull() {
	o.Set = true
	o.Null = true
	var v ResourceGroupDataTags
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilResourceGroupDataTags) Get() (v ResourceGroupDataTags, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilResourceGroupDataTags) Or(d ResourceGroupDataTags) ResourceGroupDataTags {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilResourceGroupResourceArray returns new OptNilResourceGroupResourceArray with value set to v.
func NewOptNilResourceGroupResourceArray(v []ResourceGroupResource) OptNilResourceGroupResourceArray {
	return OptNilResourceGroupResourceArray{
		Value: v,
		Set:   true,
	}
}

// OptNilResourceGroupResourceArray is optional nullable []ResourceGroupResource.
type OptNilResourceGroupResourceArray struct {
	Value []ResourceGroupResource
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilResourceGroupResourceArray was set.
func (o OptNilResourceGroupResourceArray) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilResourceGroupResourceArray) Reset() {
	var v []ResourceGroupResource
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilResourceGroupResourceArray) SetTo(v []ResourceGroupResource) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilResourceGroupResourceArray) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilResourceGroupResourceArray) SetToNull() {
	o.Set = true
	o.Null = true
	var v []ResourceGroupResource
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilResourceGroupResourceArray) Get() (v []ResourceGroupResource, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilResourceGroupResourceArray) Or(d []ResourceGroupResource) []ResourceGroupResource {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilString returns new OptNilString with value set to v.
func NewOptNilString(v string) OptNilString {
	return OptNilString{
		Value: v,
		Set:   true,
	}
}

// OptNilString is optional nullable string.
type OptNilString struct {
	Value string
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilString was set.
func (o OptNilString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilString) Reset() {
	var v string
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilString) SetTo(v string) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilString) SetToNull() {
	o.Set = true
	o.Null = true
	var v string
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptResourceGroupData returns new OptResourceGroupData with value set to v.
func NewOptResourceGroupData(v ResourceGroupData) OptResourceGroupData {
	return OptResourceGroupData{
		Value: v,
		Set:   true,
	}
}

// OptResourceGroupData is optional ResourceGroupData.
type OptResourceGroupData struct {
	Value ResourceGroupData
	Set   bool
}

// IsSet returns true if OptResourceGroupData was set.
func (o OptResourceGroupData) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptResourceGroupData) Reset() {
	var v ResourceGroupData
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptResourceGroupData) SetTo(v ResourceGroupData) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptResourceGroupData) Get() (v ResourceGroupData, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptResourceGroupData) Or(d ResourceGroupData) ResourceGroupData {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptResourceIdentifier returns new OptResourceIdentifier with value set to v.
func NewOptResourceIdentifier(v ResourceIdentifier) OptResourceIdentifier {
	return OptResourceIdentifier{
		Value: v,
		Set:   true,
	}
}

// OptResourceIdentifier is optional ResourceIdentifier.
type OptResourceIdentifier struct {
	Value ResourceIdentifier
	Set   bool
}

// IsSet returns true if OptResourceIdentifier was set.
func (o OptResourceIdentifier) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptResourceIdentifier) Reset() {
	var v ResourceIdentifier
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptResourceIdentifier) SetTo(v ResourceIdentifier) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptResourceIdentifier) Get() (v ResourceIdentifier, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptResourceIdentifier) Or(d ResourceIdentifier) ResourceIdentifier {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptResourceType returns new OptResourceType with value set to v.
func NewOptResourceType(v ResourceType) OptResourceType {
	return OptResourceType{
		Value: v,
		Set:   true,
	}
}

// OptResourceType is optional ResourceType.
type OptResourceType struct {
	Value ResourceType
	Set   bool
}

// IsSet returns true if OptResourceType was set.
func (o OptResourceType) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptResourceType) Reset() {
	var v ResourceType
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptResourceType) SetTo(v ResourceType) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptResourceType) Get() (v ResourceType, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptResourceType) Or(d ResourceType) ResourceType {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptSystemData returns new OptSystemData with value set to v.
func NewOptSystemData(v SystemData) OptSystemData {
	return OptSystemData{
		Value: v,
		Set:   true,
	}
}

// OptSystemData is optional SystemData.
type OptSystemData struct {
	Value SystemData
	Set   bool
}

// IsSet returns true if OptSystemData was set.
func (o OptSystemData) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptSystemData) Reset() {
	var v SystemData
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptSystemData) SetTo(v SystemData) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptSystemData) Get() (v SystemData, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptSystemData) Or(d SystemData) SystemData {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptURI returns new OptURI with value set to v.
func NewOptURI(v url.URL) OptURI {
	return OptURI{
		Value: v,
		Set:   true,
	}
}

// OptURI is optional url.URL.
type OptURI struct {
	Value url.URL
	Set   bool
}

// IsSet returns true if OptURI was set.
func (o OptURI) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptURI) Reset() {
	var v url.URL
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptURI) SetTo(v url.URL) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptURI) Get() (v url.URL, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptURI) Or(d url.URL) url.URL {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/PostDeploymentResponse
type PostDeploymentResponse struct {
	ResourceGroupName OptNilString `json:"resourceGroupName"`
	DeploymentName    OptNilString `json:"deploymentName"`
}

// GetResourceGroupName returns the value of ResourceGroupName.
func (s *PostDeploymentResponse) GetResourceGroupName() OptNilString {
	return s.ResourceGroupName
}

// GetDeploymentName returns the value of DeploymentName.
func (s *PostDeploymentResponse) GetDeploymentName() OptNilString {
	return s.DeploymentName
}

// SetResourceGroupName sets the value of ResourceGroupName.
func (s *PostDeploymentResponse) SetResourceGroupName(val OptNilString) {
	s.ResourceGroupName = val
}

// SetDeploymentName sets the value of DeploymentName.
func (s *PostDeploymentResponse) SetDeploymentName(val OptNilString) {
	s.DeploymentName = val
}

func (*PostDeploymentResponse) createAZ0101Res() {}
func (*PostDeploymentResponse) createAZ0102Res() {}
func (*PostDeploymentResponse) createAZ0103Res() {}
func (*PostDeploymentResponse) createAZ0104Res() {}
func (*PostDeploymentResponse) createAZ0105Res() {}
func (*PostDeploymentResponse) createAZ0107Res() {}
func (*PostDeploymentResponse) createAZ0301Res() {}
func (*PostDeploymentResponse) createAZ0401Res() {}
func (*PostDeploymentResponse) createAZ0402Res() {}
func (*PostDeploymentResponse) createAZ0501Res() {}

// Ref: #/components/schemas/PricingLevel
type PricingLevel int32

const (
	PricingLevel1 PricingLevel = 1
	PricingLevel2 PricingLevel = 2
)

// AllValues returns all PricingLevel values.
func (PricingLevel) AllValues() []PricingLevel {
	return []PricingLevel{
		PricingLevel1,
		PricingLevel2,
	}
}

// Ref: #/components/schemas/QueryPostRequestBody
type QueryPostRequestBody struct {
	Location string `json:"location"`
}

// GetLocation returns the value of Location.
func (s *QueryPostRequestBody) GetLocation() string {
	return s.Location
}

// SetLocation sets the value of Location.
func (s *QueryPostRequestBody) SetLocation(val string) {
	s.Location = val
}

// Ref: #/components/schemas/ResourceGroupData
type ResourceGroupData struct {
	ID                             *ResourceIdentifier         `json:"id"`
	Name                           OptNilString                `json:"name"`
	ResourceType                   OptResourceType             `json:"resourceType"`
	SystemData                     OptSystemData               `json:"systemData"`
	Tags                           OptNilResourceGroupDataTags `json:"tags"`
	Location                       OptAzureLocation            `json:"location"`
	ResourceGroupProvisioningState OptNilString                `json:"resourceGroupProvisioningState"`
	ManagedBy                      OptNilString                `json:"managedBy"`
}

// GetID returns the value of ID.
func (s *ResourceGroupData) GetID() *ResourceIdentifier {
	return s.ID
}

// GetName returns the value of Name.
func (s *ResourceGroupData) GetName() OptNilString {
	return s.Name
}

// GetResourceType returns the value of ResourceType.
func (s *ResourceGroupData) GetResourceType() OptResourceType {
	return s.ResourceType
}

// GetSystemData returns the value of SystemData.
func (s *ResourceGroupData) GetSystemData() OptSystemData {
	return s.SystemData
}

// GetTags returns the value of Tags.
func (s *ResourceGroupData) GetTags() OptNilResourceGroupDataTags {
	return s.Tags
}

// GetLocation returns the value of Location.
func (s *ResourceGroupData) GetLocation() OptAzureLocation {
	return s.Location
}

// GetResourceGroupProvisioningState returns the value of ResourceGroupProvisioningState.
func (s *ResourceGroupData) GetResourceGroupProvisioningState() OptNilString {
	return s.ResourceGroupProvisioningState
}

// GetManagedBy returns the value of ManagedBy.
func (s *ResourceGroupData) GetManagedBy() OptNilString {
	return s.ManagedBy
}

// SetID sets the value of ID.
func (s *ResourceGroupData) SetID(val *ResourceIdentifier) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *ResourceGroupData) SetName(val OptNilString) {
	s.Name = val
}

// SetResourceType sets the value of ResourceType.
func (s *ResourceGroupData) SetResourceType(val OptResourceType) {
	s.ResourceType = val
}

// SetSystemData sets the value of SystemData.
func (s *ResourceGroupData) SetSystemData(val OptSystemData) {
	s.SystemData = val
}

// SetTags sets the value of Tags.
func (s *ResourceGroupData) SetTags(val OptNilResourceGroupDataTags) {
	s.Tags = val
}

// SetLocation sets the value of Location.
func (s *ResourceGroupData) SetLocation(val OptAzureLocation) {
	s.Location = val
}

// SetResourceGroupProvisioningState sets the value of ResourceGroupProvisioningState.
func (s *ResourceGroupData) SetResourceGroupProvisioningState(val OptNilString) {
	s.ResourceGroupProvisioningState = val
}

// SetManagedBy sets the value of ManagedBy.
func (s *ResourceGroupData) SetManagedBy(val OptNilString) {
	s.ManagedBy = val
}

type ResourceGroupDataTags map[string]NilString

func (s *ResourceGroupDataTags) init() ResourceGroupDataTags {
	m := *s
	if m == nil {
		m = map[string]NilString{}
		*s = m
	}
	return m
}

// Ref: #/components/schemas/ResourceGroupResource
type ResourceGroupResource struct {
	ID      *ResourceIdentifier  `json:"id"`
	HasData OptBool              `json:"hasData"`
	Data    OptResourceGroupData `json:"data"`
	URL     OptURI               `json:"url"`
}

// GetID returns the value of ID.
func (s *ResourceGroupResource) GetID() *ResourceIdentifier {
	return s.ID
}

// GetHasData returns the value of HasData.
func (s *ResourceGroupResource) GetHasData() OptBool {
	return s.HasData
}

// GetData returns the value of Data.
func (s *ResourceGroupResource) GetData() OptResourceGroupData {
	return s.Data
}

// GetURL returns the value of URL.
func (s *ResourceGroupResource) GetURL() OptURI {
	return s.URL
}

// SetID sets the value of ID.
func (s *ResourceGroupResource) SetID(val *ResourceIdentifier) {
	s.ID = val
}

// SetHasData sets the value of HasData.
func (s *ResourceGroupResource) SetHasData(val OptBool) {
	s.HasData = val
}

// SetData sets the value of Data.
func (s *ResourceGroupResource) SetData(val OptResourceGroupData) {
	s.Data = val
}

// SetURL sets the value of URL.
func (s *ResourceGroupResource) SetURL(val OptURI) {
	s.URL = val
}

// Ref: #/components/schemas/ResourceIdentifier
type ResourceIdentifier struct {
	ResourceType      OptResourceType     `json:"resourceType"`
	Name              OptNilString        `json:"name"`
	Parent            *ResourceIdentifier `json:"parent"`
	SubscriptionId    OptNilString        `json:"subscriptionId"`
	Provider          OptNilString        `json:"provider"`
	Location          OptAzureLocation    `json:"location"`
	ResourceGroupName OptNilString        `json:"resourceGroupName"`
}

// GetResourceType returns the value of ResourceType.
func (s *ResourceIdentifier) GetResourceType() OptResourceType {
	return s.ResourceType
}

// GetName returns the value of Name.
func (s *ResourceIdentifier) GetName() OptNilString {
	return s.Name
}

// GetParent returns the value of Parent.
func (s *ResourceIdentifier) GetParent() *ResourceIdentifier {
	return s.Parent
}

// GetSubscriptionId returns the value of SubscriptionId.
func (s *ResourceIdentifier) GetSubscriptionId() OptNilString {
	return s.SubscriptionId
}

// GetProvider returns the value of Provider.
func (s *ResourceIdentifier) GetProvider() OptNilString {
	return s.Provider
}

// GetLocation returns the value of Location.
func (s *ResourceIdentifier) GetLocation() OptAzureLocation {
	return s.Location
}

// GetResourceGroupName returns the value of ResourceGroupName.
func (s *ResourceIdentifier) GetResourceGroupName() OptNilString {
	return s.ResourceGroupName
}

// SetResourceType sets the value of ResourceType.
func (s *ResourceIdentifier) SetResourceType(val OptResourceType) {
	s.ResourceType = val
}

// SetName sets the value of Name.
func (s *ResourceIdentifier) SetName(val OptNilString) {
	s.Name = val
}

// SetParent sets the value of Parent.
func (s *ResourceIdentifier) SetParent(val *ResourceIdentifier) {
	s.Parent = val
}

// SetSubscriptionId sets the value of SubscriptionId.
func (s *ResourceIdentifier) SetSubscriptionId(val OptNilString) {
	s.SubscriptionId = val
}

// SetProvider sets the value of Provider.
func (s *ResourceIdentifier) SetProvider(val OptNilString) {
	s.Provider = val
}

// SetLocation sets the value of Location.
func (s *ResourceIdentifier) SetLocation(val OptAzureLocation) {
	s.Location = val
}

// SetResourceGroupName sets the value of ResourceGroupName.
func (s *ResourceIdentifier) SetResourceGroupName(val OptNilString) {
	s.ResourceGroupName = val
}

// Ref: #/components/schemas/ResourceType
type ResourceType struct {
	Namespace OptNilString `json:"namespace"`
	Type      OptNilString `json:"type"`
}

// GetNamespace returns the value of Namespace.
func (s *ResourceType) GetNamespace() OptNilString {
	return s.Namespace
}

// GetType returns the value of Type.
func (s *ResourceType) GetType() OptNilString {
	return s.Type
}

// SetNamespace sets the value of Namespace.
func (s *ResourceType) SetNamespace(val OptNilString) {
	s.Namespace = val
}

// SetType sets the value of Type.
func (s *ResourceType) SetType(val OptNilString) {
	s.Type = val
}

// Ref: #/components/schemas/SearchPostRequestBody
type SearchPostRequestBody struct {
	Location       string       `json:"location"`
	Sku            SearchSku    `json:"sku"`
	SkuString      OptNilString `json:"skuString"`
	ReplicaCount   int32        `json:"replicaCount"`
	PartitionCount int32        `json:"partitionCount"`
}

// GetLocation returns the value of Location.
func (s *SearchPostRequestBody) GetLocation() string {
	return s.Location
}

// GetSku returns the value of Sku.
func (s *SearchPostRequestBody) GetSku() SearchSku {
	return s.Sku
}

// GetSkuString returns the value of SkuString.
func (s *SearchPostRequestBody) GetSkuString() OptNilString {
	return s.SkuString
}

// GetReplicaCount returns the value of ReplicaCount.
func (s *SearchPostRequestBody) GetReplicaCount() int32 {
	return s.ReplicaCount
}

// GetPartitionCount returns the value of PartitionCount.
func (s *SearchPostRequestBody) GetPartitionCount() int32 {
	return s.PartitionCount
}

// SetLocation sets the value of Location.
func (s *SearchPostRequestBody) SetLocation(val string) {
	s.Location = val
}

// SetSku sets the value of Sku.
func (s *SearchPostRequestBody) SetSku(val SearchSku) {
	s.Sku = val
}

// SetSkuString sets the value of SkuString.
func (s *SearchPostRequestBody) SetSkuString(val OptNilString) {
	s.SkuString = val
}

// SetReplicaCount sets the value of ReplicaCount.
func (s *SearchPostRequestBody) SetReplicaCount(val int32) {
	s.ReplicaCount = val
}

// SetPartitionCount sets the value of PartitionCount.
func (s *SearchPostRequestBody) SetPartitionCount(val int32) {
	s.PartitionCount = val
}

// Ref: #/components/schemas/SearchSku
type SearchSku int32

const (
	SearchSku1 SearchSku = 1
	SearchSku2 SearchSku = 2
	SearchSku3 SearchSku = 3
	SearchSku4 SearchSku = 4
	SearchSku5 SearchSku = 5
	SearchSku6 SearchSku = 6
	SearchSku7 SearchSku = 7
	SearchSku8 SearchSku = 8
)

// AllValues returns all SearchSku values.
func (SearchSku) AllValues() []SearchSku {
	return []SearchSku{
		SearchSku1,
		SearchSku2,
		SearchSku3,
		SearchSku4,
		SearchSku5,
		SearchSku6,
		SearchSku7,
		SearchSku8,
	}
}

// Ref: #/components/schemas/ServerOsType
type ServerOsType int32

const (
	ServerOsType1 ServerOsType = 1
	ServerOsType2 ServerOsType = 2
)

// AllValues returns all ServerOsType values.
func (ServerOsType) AllValues() []ServerOsType {
	return []ServerOsType{
		ServerOsType1,
		ServerOsType2,
	}
}

// Ref: #/components/schemas/StreamingRequestBody
type StreamingRequestBody struct {
	Location  string `json:"location"`
	UnitCount string `json:"unitCount"`
}

// GetLocation returns the value of Location.
func (s *StreamingRequestBody) GetLocation() string {
	return s.Location
}

// GetUnitCount returns the value of UnitCount.
func (s *StreamingRequestBody) GetUnitCount() string {
	return s.UnitCount
}

// SetLocation sets the value of Location.
func (s *StreamingRequestBody) SetLocation(val string) {
	s.Location = val
}

// SetUnitCount sets the value of UnitCount.
func (s *StreamingRequestBody) SetUnitCount(val string) {
	s.UnitCount = val
}

// Ref: #/components/schemas/SystemData
type SystemData struct {
	CreatedBy          OptNilString   `json:"createdBy"`
	CreatedByType      *CreatedByType `json:"createdByType"`
	CreatedOn          OptNilDateTime `json:"createdOn"`
	LastModifiedBy     OptNilString   `json:"lastModifiedBy"`
	LastModifiedByType *CreatedByType `json:"lastModifiedByType"`
	LastModifiedOn     OptNilDateTime `json:"lastModifiedOn"`
}

// GetCreatedBy returns the value of CreatedBy.
func (s *SystemData) GetCreatedBy() OptNilString {
	return s.CreatedBy
}

// GetCreatedByType returns the value of CreatedByType.
func (s *SystemData) GetCreatedByType() *CreatedByType {
	return s.CreatedByType
}

// GetCreatedOn returns the value of CreatedOn.
func (s *SystemData) GetCreatedOn() OptNilDateTime {
	return s.CreatedOn
}

// GetLastModifiedBy returns the value of LastModifiedBy.
func (s *SystemData) GetLastModifiedBy() OptNilString {
	return s.LastModifiedBy
}

// GetLastModifiedByType returns the value of LastModifiedByType.
func (s *SystemData) GetLastModifiedByType() *CreatedByType {
	return s.LastModifiedByType
}

// GetLastModifiedOn returns the value of LastModifiedOn.
func (s *SystemData) GetLastModifiedOn() OptNilDateTime {
	return s.LastModifiedOn
}

// SetCreatedBy sets the value of CreatedBy.
func (s *SystemData) SetCreatedBy(val OptNilString) {
	s.CreatedBy = val
}

// SetCreatedByType sets the value of CreatedByType.
func (s *SystemData) SetCreatedByType(val *CreatedByType) {
	s.CreatedByType = val
}

// SetCreatedOn sets the value of CreatedOn.
func (s *SystemData) SetCreatedOn(val OptNilDateTime) {
	s.CreatedOn = val
}

// SetLastModifiedBy sets the value of LastModifiedBy.
func (s *SystemData) SetLastModifiedBy(val OptNilString) {
	s.LastModifiedBy = val
}

// SetLastModifiedByType sets the value of LastModifiedByType.
func (s *SystemData) SetLastModifiedByType(val *CreatedByType) {
	s.LastModifiedByType = val
}

// SetLastModifiedOn sets the value of LastModifiedOn.
func (s *SystemData) SetLastModifiedOn(val OptNilDateTime) {
	s.LastModifiedOn = val
}

// Ref: #/components/schemas/VulnerabilityRequestBody
type VulnerabilityRequestBody struct {
	Location string       `json:"location"`
	Os       ServerOsType `json:"os"`
}

// GetLocation returns the value of Location.
func (s *VulnerabilityRequestBody) GetLocation() string {
	return s.Location
}

// GetOs returns the value of Os.
func (s *VulnerabilityRequestBody) GetOs() ServerOsType {
	return s.Os
}

// SetLocation sets the value of Location.
func (s *VulnerabilityRequestBody) SetLocation(val string) {
	s.Location = val
}

// SetOs sets the value of Os.
func (s *VulnerabilityRequestBody) SetOs(val ServerOsType) {
	s.Os = val
}

// Ref: #/components/schemas/VulnerabilityResponseBody
type VulnerabilityResponseBody struct {
	ResourceGroupName OptNilString `json:"resourceGroupName"`
	InstallScript     OptNilString `json:"installScript"`
}

// GetResourceGroupName returns the value of ResourceGroupName.
func (s *VulnerabilityResponseBody) GetResourceGroupName() OptNilString {
	return s.ResourceGroupName
}

// GetInstallScript returns the value of InstallScript.
func (s *VulnerabilityResponseBody) GetInstallScript() OptNilString {
	return s.InstallScript
}

// SetResourceGroupName sets the value of ResourceGroupName.
func (s *VulnerabilityResponseBody) SetResourceGroupName(val OptNilString) {
	s.ResourceGroupName = val
}

// SetInstallScript sets the value of InstallScript.
func (s *VulnerabilityResponseBody) SetInstallScript(val OptNilString) {
	s.InstallScript = val
}

func (*VulnerabilityResponseBody) createAZ0403Res() {}

// Ref: #/components/schemas/WafRequestBody
type WafRequestBody struct {
	Location string            `json:"location"`
	Profile  FrontDoorProfile  `json:"profile"`
	Endpoint FrontDoorEndpoint `json:"endpoint"`
}

// GetLocation returns the value of Location.
func (s *WafRequestBody) GetLocation() string {
	return s.Location
}

// GetProfile returns the value of Profile.
func (s *WafRequestBody) GetProfile() FrontDoorProfile {
	return s.Profile
}

// GetEndpoint returns the value of Endpoint.
func (s *WafRequestBody) GetEndpoint() FrontDoorEndpoint {
	return s.Endpoint
}

// SetLocation sets the value of Location.
func (s *WafRequestBody) SetLocation(val string) {
	s.Location = val
}

// SetProfile sets the value of Profile.
func (s *WafRequestBody) SetProfile(val FrontDoorProfile) {
	s.Profile = val
}

// SetEndpoint sets the value of Endpoint.
func (s *WafRequestBody) SetEndpoint(val FrontDoorEndpoint) {
	s.Endpoint = val
}
