// Code generated by ogen, DO NOT EDIT.
package v1

type CreateAZ0101Res interface {
	createAZ0101Res()
}

type CreateAZ0102Res interface {
	createAZ0102Res()
}

type CreateAZ0103Res interface {
	createAZ0103Res()
}

type CreateAZ0104Res interface {
	createAZ0104Res()
}

type CreateAZ0105Res interface {
	createAZ0105Res()
}

type CreateAZ0107Res interface {
	createAZ0107Res()
}

type CreateAZ0301Res interface {
	createAZ0301Res()
}

type CreateAZ0401Res interface {
	createAZ0401Res()
}

type CreateAZ0402Res interface {
	createAZ0402Res()
}

type CreateAZ0403Res interface {
	createAZ0403Res()
}

type CreateAZ0501Res interface {
	createAZ0501Res()
}

type DeleteAZ0101Res interface {
	deleteAZ0101Res()
}

type DeleteAZ0102Res interface {
	deleteAZ0102Res()
}

type DeleteAZ0103Res interface {
	deleteAZ0103Res()
}

type DeleteAZ0104Res interface {
	deleteAZ0104Res()
}

type DeleteAZ0105Res interface {
	deleteAZ0105Res()
}

type DeleteAZ0107Res interface {
	deleteAZ0107Res()
}

type DeleteAZ0301Res interface {
	deleteAZ0301Res()
}

type DeleteAZ0401Res interface {
	deleteAZ0401Res()
}

type DeleteAZ0402Res interface {
	deleteAZ0402Res()
}

type DeleteAZ0403Res interface {
	deleteAZ0403Res()
}

type DeleteAZ0501Res interface {
	deleteAZ0501Res()
}

type GetAZ0101Res interface {
	getAZ0101Res()
}

type GetAZ0102Res interface {
	getAZ0102Res()
}

type GetAZ0103Res interface {
	getAZ0103Res()
}

type GetAZ0104Res interface {
	getAZ0104Res()
}

type GetAZ0105Res interface {
	getAZ0105Res()
}

type GetAZ0107Res interface {
	getAZ0107Res()
}

type GetAZ0301Res interface {
	getAZ0301Res()
}

type GetAZ0401Res interface {
	getAZ0401Res()
}

type GetAZ0402Res interface {
	getAZ0402Res()
}

type GetAZ0403Res interface {
	getAZ0403Res()
}

type GetAZ0501Res interface {
	getAZ0501Res()
}

type ListAZ0101Res interface {
	listAZ0101Res()
}

type ListAZ0102Res interface {
	listAZ0102Res()
}

type ListAZ0103Res interface {
	listAZ0103Res()
}

type ListAZ0104Res interface {
	listAZ0104Res()
}

type ListAZ0105Res interface {
	listAZ0105Res()
}

type ListAZ0107Res interface {
	listAZ0107Res()
}

type ListAZ0301Res interface {
	listAZ0301Res()
}

type ListAZ0401Res interface {
	listAZ0401Res()
}

type ListAZ0402Res interface {
	listAZ0402Res()
}

type ListAZ0403Res interface {
	listAZ0403Res()
}

type ListAZ0501Res interface {
	listAZ0501Res()
}

type StatusAZ0101Res interface {
	statusAZ0101Res()
}

type StatusAZ0102Res interface {
	statusAZ0102Res()
}

type StatusAZ0103Res interface {
	statusAZ0103Res()
}

type StatusAZ0104Res interface {
	statusAZ0104Res()
}

type StatusAZ0105Res interface {
	statusAZ0105Res()
}

type StatusAZ0107Res interface {
	statusAZ0107Res()
}

type StatusAZ0301Res interface {
	statusAZ0301Res()
}

type StatusAZ0401Res interface {
	statusAZ0401Res()
}

type StatusAZ0402Res interface {
	statusAZ0402Res()
}

type StatusAZ0501Res interface {
	statusAZ0501Res()
}
