# Copyright 2026- The sacloud/sacloud-sdk-go Authors
# SPDX-License-Identifier: Apache-2.0

AUTHOR ?= The sacloud/sacloud-sdk-go Authors
SACLOUD_SDK_GO_ROOT := $(abspath $(dir $(lastword $(MAKEFILE_LIST)))/..)
include $(SACLOUD_SDK_GO_ROOT)/makefiles/go/common.mk

.PHONY: default tools
default: $(DEFAULT_GOALS)
tools: dev-tools