// Copyright 2022-2025 The sacloud/dedicated-storage-api-go Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by ogen, DO NOT EDIT.

package v1

import (
	"context"
	"net/url"
	"strings"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	ht "github.com/ogen-go/ogen/http"
	"github.com/ogen-go/ogen/uri"
)

func trimTrailingSlashes(u *url.URL) {
	u.Path = strings.TrimRight(u.Path, "/")
	u.RawPath = strings.TrimRight(u.RawPath, "/")
}

// Invoker invokes operations described by OpenAPI v3 specification.
type Invoker interface {
	// DedicatedStorageContractsCreate invokes DedicatedStorageContracts_create operation.
	//
	// 専有ストレージ契約作成.
	//
	// POST /dedicatedstoragecontract
	DedicatedStorageContractsCreate(ctx context.Context, request *CreateDedicatedStorageContractRequest) (*DedicatedStorageContractResponse, error)
	// DedicatedStorageContractsDelete invokes DedicatedStorageContracts_delete operation.
	//
	// 専有ストレージ解約.
	//
	// DELETE /dedicatedstoragecontract/{id}
	DedicatedStorageContractsDelete(ctx context.Context, params DedicatedStorageContractsDeleteParams) error
	// DedicatedStorageContractsGet invokes DedicatedStorageContracts_get operation.
	//
	// 専有ストレージ単体取得.
	//
	// GET /dedicatedstoragecontract/{id}
	DedicatedStorageContractsGet(ctx context.Context, params DedicatedStorageContractsGetParams) (*DedicatedStorageContractResponse, error)
	// DedicatedStorageContractsList invokes DedicatedStorageContracts_list operation.
	//
	// 専有ストレージ一覧.
	//
	// GET /dedicatedstoragecontract
	DedicatedStorageContractsList(ctx context.Context) (*DedicatedStorageContractsListResponse, error)
	// DedicatedStorageContractsListSnapshotsByContract invokes DedicatedStorageContracts_listSnapshotsByContract operation.
	//
	// スナップショット専有ストレージ単位の一覧.
	//
	// GET /dedicatedstoragecontract/{contractId}/disksnapshot
	DedicatedStorageContractsListSnapshotsByContract(ctx context.Context, params DedicatedStorageContractsListSnapshotsByContractParams) (*DiskSnapshotsListResponse, error)
	// DedicatedStorageContractsPoolUsage invokes DedicatedStorageContracts_poolUsage operation.
	//
	// 専有ストレージ使用状況取得.
	//
	// GET /dedicatedstoragecontract/{id}/poolusage
	DedicatedStorageContractsPoolUsage(ctx context.Context, params DedicatedStorageContractsPoolUsageParams) (*PoolUsageResponse, error)
	// DedicatedStorageContractsUpdate invokes DedicatedStorageContracts_update operation.
	//
	// IDおよびPlan.IDは更新できません。リクエストに含めても無視されます。.
	//
	// PUT /dedicatedstoragecontract/{id}
	DedicatedStorageContractsUpdate(ctx context.Context, request *UpdateDedicatedStorageContractRequest, params DedicatedStorageContractsUpdateParams) (*DedicatedStorageContractResponse, error)
	// DisksCreateSnapshot invokes Disks_createSnapshot operation.
	//
	// スナップショット作成.
	//
	// POST /disk/{diskId}/disksnapshot
	DisksCreateSnapshot(ctx context.Context, request *CreateSnapshotRequest, params DisksCreateSnapshotParams) (*DiskSnapshotResponse, error)
	// DisksDeleteSnapshot invokes Disks_deleteSnapshot operation.
	//
	// スナップショット削除.
	//
	// DELETE /disk/{diskId}/disksnapshot/{snapshotId}
	DisksDeleteSnapshot(ctx context.Context, params DisksDeleteSnapshotParams) error
	// DisksExpand invokes Disks_expand operation.
	//
	// オンライン容量拡張.
	//
	// PUT /disk/{id}/expand
	DisksExpand(ctx context.Context, request *ExpandDiskRequest, params DisksExpandParams) error
	// DisksListSnapshots invokes Disks_listSnapshots operation.
	//
	// スナップショットディスク単位の一覧.
	//
	// GET /disk/{diskId}/disksnapshot
	DisksListSnapshots(ctx context.Context, params DisksListSnapshotsParams) (*DiskSnapshotsListResponse, error)
	// DisksRestoreSnapshot invokes Disks_restoreSnapshot operation.
	//
	// スナップショットからのリストア.
	//
	// PUT /disk/{diskId}/disksnapshot/{snapshotId}/restore
	DisksRestoreSnapshot(ctx context.Context, params DisksRestoreSnapshotParams) error
	// DisksUpdateSnapshot invokes Disks_updateSnapshot operation.
	//
	// スナップショットの更新.
	//
	// PUT /disk/{diskId}/disksnapshot/{snapshotId}
	DisksUpdateSnapshot(ctx context.Context, request *UpdateSnapshotRequest, params DisksUpdateSnapshotParams) (*DiskSnapshotResponse, error)
	// ProductPlansGetPlans invokes ProductPlans_getPlans operation.
	//
	// 専有ストレージプラン単体取得.
	//
	// GET /product/dedicatedstoragecontractplan/{id}
	ProductPlansGetPlans(ctx context.Context, params ProductPlansGetPlansParams) (*DedicatedStorageContractPlanResponse, error)
	// ProductPlansListPlans invokes ProductPlans_listPlans operation.
	//
	// 専有ストレージプラン一覧.
	//
	// GET /product/dedicatedstoragecontractplan
	ProductPlansListPlans(ctx context.Context) (*DedicatedStorageContractPlanListResponse, error)
}

// Client implements OAS client.
type Client struct {
	serverURL *url.URL
	baseClient
}

// NewClient initializes new Client defined by OAS.
func NewClient(serverURL string, opts ...ClientOption) (*Client, error) {
	u, err := url.Parse(serverURL)
	if err != nil {
		return nil, err
	}
	trimTrailingSlashes(u)

	c, err := newClientConfig(opts...).baseClient()
	if err != nil {
		return nil, err
	}
	return &Client{
		serverURL:  u,
		baseClient: c,
	}, nil
}

type serverURLKey struct{}

// WithServerURL sets context key to override server URL.
func WithServerURL(ctx context.Context, u *url.URL) context.Context {
	return context.WithValue(ctx, serverURLKey{}, u)
}

func (c *Client) requestURL(ctx context.Context) *url.URL {
	u, ok := ctx.Value(serverURLKey{}).(*url.URL)
	if !ok {
		return c.serverURL
	}
	return u
}

// DedicatedStorageContractsCreate invokes DedicatedStorageContracts_create operation.
//
// 専有ストレージ契約作成.
//
// POST /dedicatedstoragecontract
func (c *Client) DedicatedStorageContractsCreate(ctx context.Context, request *CreateDedicatedStorageContractRequest) (*DedicatedStorageContractResponse, error) {
	res, err := c.sendDedicatedStorageContractsCreate(ctx, request)
	return res, err
}

func (c *Client) sendDedicatedStorageContractsCreate(ctx context.Context, request *CreateDedicatedStorageContractRequest) (res *DedicatedStorageContractResponse, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/dedicatedstoragecontract"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeDedicatedStorageContractsCreateRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeDedicatedStorageContractsCreateResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// DedicatedStorageContractsDelete invokes DedicatedStorageContracts_delete operation.
//
// 専有ストレージ解約.
//
// DELETE /dedicatedstoragecontract/{id}
func (c *Client) DedicatedStorageContractsDelete(ctx context.Context, params DedicatedStorageContractsDeleteParams) error {
	_, err := c.sendDedicatedStorageContractsDelete(ctx, params)
	return err
}

func (c *Client) sendDedicatedStorageContractsDelete(ctx context.Context, params DedicatedStorageContractsDeleteParams) (res *DedicatedStorageContractsDeleteOK, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/dedicatedstoragecontract/"
	{
		// Encode "id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.Int64ToString(params.ID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "DELETE", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeDedicatedStorageContractsDeleteResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// DedicatedStorageContractsGet invokes DedicatedStorageContracts_get operation.
//
// 専有ストレージ単体取得.
//
// GET /dedicatedstoragecontract/{id}
func (c *Client) DedicatedStorageContractsGet(ctx context.Context, params DedicatedStorageContractsGetParams) (*DedicatedStorageContractResponse, error) {
	res, err := c.sendDedicatedStorageContractsGet(ctx, params)
	return res, err
}

func (c *Client) sendDedicatedStorageContractsGet(ctx context.Context, params DedicatedStorageContractsGetParams) (res *DedicatedStorageContractResponse, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/dedicatedstoragecontract/"
	{
		// Encode "id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.Int64ToString(params.ID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeDedicatedStorageContractsGetResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// DedicatedStorageContractsList invokes DedicatedStorageContracts_list operation.
//
// 専有ストレージ一覧.
//
// GET /dedicatedstoragecontract
func (c *Client) DedicatedStorageContractsList(ctx context.Context) (*DedicatedStorageContractsListResponse, error) {
	res, err := c.sendDedicatedStorageContractsList(ctx)
	return res, err
}

func (c *Client) sendDedicatedStorageContractsList(ctx context.Context) (res *DedicatedStorageContractsListResponse, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/dedicatedstoragecontract"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeDedicatedStorageContractsListResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// DedicatedStorageContractsListSnapshotsByContract invokes DedicatedStorageContracts_listSnapshotsByContract operation.
//
// スナップショット専有ストレージ単位の一覧.
//
// GET /dedicatedstoragecontract/{contractId}/disksnapshot
func (c *Client) DedicatedStorageContractsListSnapshotsByContract(ctx context.Context, params DedicatedStorageContractsListSnapshotsByContractParams) (*DiskSnapshotsListResponse, error) {
	res, err := c.sendDedicatedStorageContractsListSnapshotsByContract(ctx, params)
	return res, err
}

func (c *Client) sendDedicatedStorageContractsListSnapshotsByContract(ctx context.Context, params DedicatedStorageContractsListSnapshotsByContractParams) (res *DiskSnapshotsListResponse, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/dedicatedstoragecontract/"
	{
		// Encode "contractId" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "contractId",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.Int64ToString(params.ContractId))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/disksnapshot"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeDedicatedStorageContractsListSnapshotsByContractResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// DedicatedStorageContractsPoolUsage invokes DedicatedStorageContracts_poolUsage operation.
//
// 専有ストレージ使用状況取得.
//
// GET /dedicatedstoragecontract/{id}/poolusage
func (c *Client) DedicatedStorageContractsPoolUsage(ctx context.Context, params DedicatedStorageContractsPoolUsageParams) (*PoolUsageResponse, error) {
	res, err := c.sendDedicatedStorageContractsPoolUsage(ctx, params)
	return res, err
}

func (c *Client) sendDedicatedStorageContractsPoolUsage(ctx context.Context, params DedicatedStorageContractsPoolUsageParams) (res *PoolUsageResponse, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/dedicatedstoragecontract/"
	{
		// Encode "id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.Int64ToString(params.ID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/poolusage"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeDedicatedStorageContractsPoolUsageResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// DedicatedStorageContractsUpdate invokes DedicatedStorageContracts_update operation.
//
// IDおよびPlan.IDは更新できません。リクエストに含めても無視されます。.
//
// PUT /dedicatedstoragecontract/{id}
func (c *Client) DedicatedStorageContractsUpdate(ctx context.Context, request *UpdateDedicatedStorageContractRequest, params DedicatedStorageContractsUpdateParams) (*DedicatedStorageContractResponse, error) {
	res, err := c.sendDedicatedStorageContractsUpdate(ctx, request, params)
	return res, err
}

func (c *Client) sendDedicatedStorageContractsUpdate(ctx context.Context, request *UpdateDedicatedStorageContractRequest, params DedicatedStorageContractsUpdateParams) (res *DedicatedStorageContractResponse, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/dedicatedstoragecontract/"
	{
		// Encode "id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.Int64ToString(params.ID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "PUT", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeDedicatedStorageContractsUpdateRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeDedicatedStorageContractsUpdateResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// DisksCreateSnapshot invokes Disks_createSnapshot operation.
//
// スナップショット作成.
//
// POST /disk/{diskId}/disksnapshot
func (c *Client) DisksCreateSnapshot(ctx context.Context, request *CreateSnapshotRequest, params DisksCreateSnapshotParams) (*DiskSnapshotResponse, error) {
	res, err := c.sendDisksCreateSnapshot(ctx, request, params)
	return res, err
}

func (c *Client) sendDisksCreateSnapshot(ctx context.Context, request *CreateSnapshotRequest, params DisksCreateSnapshotParams) (res *DiskSnapshotResponse, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/disk/"
	{
		// Encode "diskId" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "diskId",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.Int64ToString(params.DiskId))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/disksnapshot"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeDisksCreateSnapshotRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeDisksCreateSnapshotResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// DisksDeleteSnapshot invokes Disks_deleteSnapshot operation.
//
// スナップショット削除.
//
// DELETE /disk/{diskId}/disksnapshot/{snapshotId}
func (c *Client) DisksDeleteSnapshot(ctx context.Context, params DisksDeleteSnapshotParams) error {
	_, err := c.sendDisksDeleteSnapshot(ctx, params)
	return err
}

func (c *Client) sendDisksDeleteSnapshot(ctx context.Context, params DisksDeleteSnapshotParams) (res *DisksDeleteSnapshotOK, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [4]string
	pathParts[0] = "/disk/"
	{
		// Encode "diskId" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "diskId",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.Int64ToString(params.DiskId))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/disksnapshot/"
	{
		// Encode "snapshotId" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "snapshotId",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.Int64ToString(params.SnapshotId))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[3] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "DELETE", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeDisksDeleteSnapshotResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// DisksExpand invokes Disks_expand operation.
//
// オンライン容量拡張.
//
// PUT /disk/{id}/expand
func (c *Client) DisksExpand(ctx context.Context, request *ExpandDiskRequest, params DisksExpandParams) error {
	_, err := c.sendDisksExpand(ctx, request, params)
	return err
}

func (c *Client) sendDisksExpand(ctx context.Context, request *ExpandDiskRequest, params DisksExpandParams) (res *DisksExpandAccepted, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/disk/"
	{
		// Encode "id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.Int64ToString(params.ID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/expand"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "PUT", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeDisksExpandRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeDisksExpandResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// DisksListSnapshots invokes Disks_listSnapshots operation.
//
// スナップショットディスク単位の一覧.
//
// GET /disk/{diskId}/disksnapshot
func (c *Client) DisksListSnapshots(ctx context.Context, params DisksListSnapshotsParams) (*DiskSnapshotsListResponse, error) {
	res, err := c.sendDisksListSnapshots(ctx, params)
	return res, err
}

func (c *Client) sendDisksListSnapshots(ctx context.Context, params DisksListSnapshotsParams) (res *DiskSnapshotsListResponse, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/disk/"
	{
		// Encode "diskId" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "diskId",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.Int64ToString(params.DiskId))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/disksnapshot"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeDisksListSnapshotsResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// DisksRestoreSnapshot invokes Disks_restoreSnapshot operation.
//
// スナップショットからのリストア.
//
// PUT /disk/{diskId}/disksnapshot/{snapshotId}/restore
func (c *Client) DisksRestoreSnapshot(ctx context.Context, params DisksRestoreSnapshotParams) error {
	_, err := c.sendDisksRestoreSnapshot(ctx, params)
	return err
}

func (c *Client) sendDisksRestoreSnapshot(ctx context.Context, params DisksRestoreSnapshotParams) (res *DisksRestoreSnapshotAccepted, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [5]string
	pathParts[0] = "/disk/"
	{
		// Encode "diskId" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "diskId",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.Int64ToString(params.DiskId))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/disksnapshot/"
	{
		// Encode "snapshotId" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "snapshotId",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.Int64ToString(params.SnapshotId))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[3] = encoded
	}
	pathParts[4] = "/restore"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "PUT", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeDisksRestoreSnapshotResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// DisksUpdateSnapshot invokes Disks_updateSnapshot operation.
//
// スナップショットの更新.
//
// PUT /disk/{diskId}/disksnapshot/{snapshotId}
func (c *Client) DisksUpdateSnapshot(ctx context.Context, request *UpdateSnapshotRequest, params DisksUpdateSnapshotParams) (*DiskSnapshotResponse, error) {
	res, err := c.sendDisksUpdateSnapshot(ctx, request, params)
	return res, err
}

func (c *Client) sendDisksUpdateSnapshot(ctx context.Context, request *UpdateSnapshotRequest, params DisksUpdateSnapshotParams) (res *DiskSnapshotResponse, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [4]string
	pathParts[0] = "/disk/"
	{
		// Encode "diskId" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "diskId",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.Int64ToString(params.DiskId))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/disksnapshot/"
	{
		// Encode "snapshotId" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "snapshotId",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.Int64ToString(params.SnapshotId))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[3] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "PUT", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeDisksUpdateSnapshotRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeDisksUpdateSnapshotResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// ProductPlansGetPlans invokes ProductPlans_getPlans operation.
//
// 専有ストレージプラン単体取得.
//
// GET /product/dedicatedstoragecontractplan/{id}
func (c *Client) ProductPlansGetPlans(ctx context.Context, params ProductPlansGetPlansParams) (*DedicatedStorageContractPlanResponse, error) {
	res, err := c.sendProductPlansGetPlans(ctx, params)
	return res, err
}

func (c *Client) sendProductPlansGetPlans(ctx context.Context, params ProductPlansGetPlansParams) (res *DedicatedStorageContractPlanResponse, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/product/dedicatedstoragecontractplan/"
	{
		// Encode "id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.Int64ToString(params.ID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeProductPlansGetPlansResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// ProductPlansListPlans invokes ProductPlans_listPlans operation.
//
// 専有ストレージプラン一覧.
//
// GET /product/dedicatedstoragecontractplan
func (c *Client) ProductPlansListPlans(ctx context.Context) (*DedicatedStorageContractPlanListResponse, error) {
	res, err := c.sendProductPlansListPlans(ctx)
	return res, err
}

func (c *Client) sendProductPlansListPlans(ctx context.Context) (res *DedicatedStorageContractPlanListResponse, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/product/dedicatedstoragecontractplan"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeProductPlansListPlansResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}
