// Code generated by ogen, DO NOT EDIT.
package v1

type CreateCommonServiceItemRes interface {
	createCommonServiceItemRes()
}

type DeleteCommonServiceItemRes interface {
	deleteCommonServiceItemRes()
}

type GetCommonServiceItemRes interface {
	getCommonServiceItemRes()
}

type GetCommonServiceItemsRes interface {
	getCommonServiceItemsRes()
}

type SetProcessConfigurationSecretRes interface {
	setProcessConfigurationSecretRes()
}

type UpdateCommonServiceItemRes interface {
	updateCommonServiceItemRes()
}
