// Code generated by ogen, DO NOT EDIT.

package v1

import (
	"context"
	"net/http"

	"github.com/go-faster/errors"
)

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// ApiKeyAuth provides ApiKeyAuth security value.
	// APIキーを利用したBasic認証.
	ApiKeyAuth(ctx context.Context, operationName OperationName) (ApiKeyAuth, error)
}

// operationRolesApiKeyAuth is a private map storing roles per operation.
var operationRolesApiKeyAuth = map[string][]string{
	CancelExecutionOperation:             []string{},
	CreateExecutionOperation:             []string{},
	CreateSubscriptionOperation:          []string{},
	CreateWorkflowOperation:              []string{},
	CreateWorkflowRevisionOperation:      []string{},
	DeleteExecutionOperation:             []string{},
	DeleteSubscriptionOperation:          []string{},
	DeleteWorkflowOperation:              []string{},
	DeleteWorkflowRevisionAliasOperation: []string{},
	GetExecutionOperation:                []string{},
	GetSubscriptionOperation:             []string{},
	GetWorkflowOperation:                 []string{},
	GetWorkflowRevisionsOperation:        []string{},
	ListExecutionOperation:               []string{},
	ListExecutionHistoryOperation:        []string{},
	ListPlansOperation:                   []string{},
	ListWorkflowOperation:                []string{},
	ListWorkflowRevisionsOperation:       []string{},
	ListWorkflowSuggestOperation:         []string{},
	UpdateWorkflowOperation:              []string{},
	UpdateWorkflowRevisionAliasOperation: []string{},
}

// GetRolesForApiKeyAuth returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForApiKeyAuth(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForApiKeyAuth(operation string) []string {
	roles, ok := operationRolesApiKeyAuth[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

func (s *Client) securityApiKeyAuth(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.ApiKeyAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"ApiKeyAuth\"")
	}
	req.SetBasicAuth(t.Username, t.Password)
	return nil
}
