// Code generated by ogen, DO NOT EDIT.

package v1

// CreateApplicationVersionParams is parameters of createApplicationVersion operation.
type CreateApplicationVersionParams struct {
	ApplicationID ApplicationID
}

// CreateAutoScalingGroupParams is parameters of createAutoScalingGroup operation.
type CreateAutoScalingGroupParams struct {
	ClusterID ClusterID
}

// CreateCertificateParams is parameters of createCertificate operation.
type CreateCertificateParams struct {
	ClusterID ClusterID
}

// CreateLoadBalancerParams is parameters of createLoadBalancer operation.
type CreateLoadBalancerParams struct {
	ClusterID          ClusterID
	AutoScalingGroupID AutoScalingGroupID
}

// DeleteApplicationParams is parameters of deleteApplication operation.
type DeleteApplicationParams struct {
	ApplicationID ApplicationID
}

// DeleteApplicationVersionParams is parameters of deleteApplicationVersion operation.
type DeleteApplicationVersionParams struct {
	ApplicationID ApplicationID
	Version       ApplicationVersionNumber
}

// DeleteAutoScalingGroupParams is parameters of deleteAutoScalingGroup operation.
type DeleteAutoScalingGroupParams struct {
	ClusterID          ClusterID
	AutoScalingGroupID AutoScalingGroupID
}

// DeleteCertificateParams is parameters of deleteCertificate operation.
type DeleteCertificateParams struct {
	ClusterID     ClusterID
	CertificateID CertificateID
}

// DeleteClusterParams is parameters of deleteCluster operation.
type DeleteClusterParams struct {
	ClusterID ClusterID
}

// DeleteLoadBalancerParams is parameters of deleteLoadBalancer operation.
type DeleteLoadBalancerParams struct {
	ClusterID          ClusterID
	AutoScalingGroupID AutoScalingGroupID
	LoadBalancerID     LoadBalancerID
}

// GetApplicationParams is parameters of getApplication operation.
type GetApplicationParams struct {
	ApplicationID ApplicationID
}

// GetApplicationContainersParams is parameters of getApplicationContainers operation.
type GetApplicationContainersParams struct {
	ApplicationID ApplicationID
}

// GetApplicationVersionParams is parameters of getApplicationVersion operation.
type GetApplicationVersionParams struct {
	ApplicationID ApplicationID
	Version       ApplicationVersionNumber
}

// GetAutoScalingGroupParams is parameters of getAutoScalingGroup operation.
type GetAutoScalingGroupParams struct {
	ClusterID          ClusterID
	AutoScalingGroupID AutoScalingGroupID
}

// GetCertificateParams is parameters of getCertificate operation.
type GetCertificateParams struct {
	ClusterID     ClusterID
	CertificateID CertificateID
}

// GetClusterParams is parameters of getCluster operation.
type GetClusterParams struct {
	ClusterID ClusterID
}

// GetLoadBalancerParams is parameters of getLoadBalancer operation.
type GetLoadBalancerParams struct {
	ClusterID          ClusterID
	AutoScalingGroupID AutoScalingGroupID
	LoadBalancerID     LoadBalancerID
}

// GetLoadBalancerNodeParams is parameters of getLoadBalancerNode operation.
type GetLoadBalancerNodeParams struct {
	ClusterID          ClusterID
	AutoScalingGroupID AutoScalingGroupID
	LoadBalancerID     LoadBalancerID
	LoadBalancerNodeID LoadBalancerNodeID
}

// GetWorkerNodeParams is parameters of getWorkerNode operation.
type GetWorkerNodeParams struct {
	ClusterID          ClusterID
	AutoScalingGroupID AutoScalingGroupID
	WorkerNodeID       WorkerNodeID
}

// ListApplicationVersionsParams is parameters of listApplicationVersions operation.
type ListApplicationVersionsParams struct {
	ApplicationID ApplicationID
	// 前ページの最後のID。これ以降のデータを取得するためのカーソル。.
	Cursor   OptApplicationVersionNumber `json:",omitempty,omitzero"`
	MaxItems int64
}

// ListApplicationsParams is parameters of listApplications operation.
type ListApplicationsParams struct {
	ClusterID OptClusterID `json:",omitempty,omitzero"`
	// 前ページの最後のID。これ以降のデータを取得するためのカーソル。ページネーションに利用します。.
	Cursor OptString `json:",omitempty,omitzero"`
	// 1ページあたりの最大取得件数。.
	MaxItems int64
}

// ListAutoScalingGroupsParams is parameters of listAutoScalingGroups operation.
type ListAutoScalingGroupsParams struct {
	ClusterID              ClusterID
	LastAutoScalingGroupID OptAutoScalingGroupID `json:",omitempty,omitzero"`
	// 前ページの最後のID。これ以降のデータを取得するためのカーソル。.
	Cursor   OptAutoScalingGroupID `json:",omitempty,omitzero"`
	MaxItems int64
}

// ListCertificateParams is parameters of listCertificate operation.
type ListCertificateParams struct {
	ClusterID         ClusterID
	LastCertificateID OptCertificateID `json:",omitempty,omitzero"`
	// 前ページの最後のID。これ以降のデータを取得するためのカーソル。.
	Cursor   OptCertificateID `json:",omitempty,omitzero"`
	MaxItems int64
}

// ListClustersParams is parameters of listClusters operation.
type ListClustersParams struct {
	LastClusterID OptClusterID `json:",omitempty,omitzero"`
	// 前ページの最後のID。これ以降のデータを取得するためのカーソル。.
	Cursor   OptClusterID `json:",omitempty,omitzero"`
	MaxItems int64
}

// ListLoadBalancerNodesParams is parameters of listLoadBalancerNodes operation.
type ListLoadBalancerNodesParams struct {
	ClusterID          ClusterID
	AutoScalingGroupID AutoScalingGroupID
	LoadBalancerID     LoadBalancerID
	Cursor             OptLoadBalancerID `json:",omitempty,omitzero"`
	MaxItems           int64
}

// ListLoadBalancersParams is parameters of listLoadBalancers operation.
type ListLoadBalancersParams struct {
	ClusterID          ClusterID
	AutoScalingGroupID AutoScalingGroupID
	Cursor             OptLoadBalancerID `json:",omitempty,omitzero"`
	MaxItems           int64
}

// ListWorkerNodesParams is parameters of listWorkerNodes operation.
type ListWorkerNodesParams struct {
	ClusterID          ClusterID
	AutoScalingGroupID AutoScalingGroupID
	Cursor             OptWorkerNodeID `json:",omitempty,omitzero"`
	MaxItems           int64
}

// UpdateApplicationParams is parameters of updateApplication operation.
type UpdateApplicationParams struct {
	ApplicationID ApplicationID
}

// UpdateCertificateParams is parameters of updateCertificate operation.
type UpdateCertificateParams struct {
	ClusterID     ClusterID
	CertificateID CertificateID
}

// UpdateClusterParams is parameters of updateCluster operation.
type UpdateClusterParams struct {
	ClusterID ClusterID
}

// UpdateWorkerNodeDrainingStateParams is parameters of updateWorkerNodeDrainingState operation.
type UpdateWorkerNodeDrainingStateParams struct {
	ClusterID          ClusterID
	AutoScalingGroupID AutoScalingGroupID
	WorkerNodeID       WorkerNodeID
}
