// Code generated by ogen, DO NOT EDIT.

package v1

// ChangeKeyStatusParams is parameters of changeKeyStatus operation.
type ChangeKeyStatusParams struct {
	ResourceID string
}

// DecryptDataWithKeyParams is parameters of decryptDataWithKey operation.
type DecryptDataWithKeyParams struct {
	ResourceID string
}

// DeleteKeyParams is parameters of deleteKey operation.
type DeleteKeyParams struct {
	ResourceID string
}

// EncryptDataWithKeyParams is parameters of encryptDataWithKey operation.
type EncryptDataWithKeyParams struct {
	ResourceID string
}

// ListKeysParams is parameters of listKeys operation.
type ListKeysParams struct {
	// Number of results to return per page.
	Count OptInt `json:",omitempty,omitzero"`
	// The initial index from which to return the results.
	From OptInt `json:",omitempty,omitzero"`
}

// ReadKeyParams is parameters of readKey operation.
type ReadKeyParams struct {
	ResourceID string
}

// RotateKeyParams is parameters of rotateKey operation.
type RotateKeyParams struct {
	ResourceID string
}

// ScheduleKeyDestructionParams is parameters of scheduleKeyDestruction operation.
type ScheduleKeyDestructionParams struct {
	ResourceID string
}

// UpdateKeyParams is parameters of updateKey operation.
type UpdateKeyParams struct {
	ResourceID string
}
