// Code generated by ogen, DO NOT EDIT.

package v1

// OperationName is the ogen operation name
type OperationName = string

const (
	DeleteApplicationOperation           OperationName = "DeleteApplication"
	DeleteApplicationVersionOperation    OperationName = "DeleteApplicationVersion"
	GetApplicationOperation              OperationName = "GetApplication"
	GetApplicationStatusOperation        OperationName = "GetApplicationStatus"
	GetApplicationVersionOperation       OperationName = "GetApplicationVersion"
	GetApplicationVersionStatusOperation OperationName = "GetApplicationVersionStatus"
	GetPacketFilterOperation             OperationName = "GetPacketFilter"
	GetUserOperation                     OperationName = "GetUser"
	ListApplicationTrafficsOperation     OperationName = "ListApplicationTraffics"
	ListApplicationVersionsOperation     OperationName = "ListApplicationVersions"
	ListApplicationsOperation            OperationName = "ListApplications"
	PatchApplicationOperation            OperationName = "PatchApplication"
	PatchPacketFilterOperation           OperationName = "PatchPacketFilter"
	PostApplicationOperation             OperationName = "PostApplication"
	PostUserOperation                    OperationName = "PostUser"
	PutApplicationTrafficOperation       OperationName = "PutApplicationTraffic"
)
