// Code generated by ogen, DO NOT EDIT.

package v1

import (
	"time"
)

// SetFake set fake values.
func (s *ContainerRegistryAction) SetFake() {
	*s = ContainerRegistryActionNew
}

// SetFake set fake values.
func (s *CreateApplicationBadRequest) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *CreateApplicationBody) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.TimeoutSeconds = int(0)
		}
	}
	{
		{
			s.Port = int(0)
		}
	}
	{
		{
			s.MinScale = int(0)
		}
	}
	{
		{
			s.MaxScale = int(0)
		}
	}
	{
		{
			s.ScaleTargetConcurrency.SetFake()
		}
	}
	{
		{
			s.Components = nil
			for i := 0; i < 0; i++ {
				var elem CreateApplicationBodyComponentsItem
				{
					elem.SetFake()
				}
				s.Components = append(s.Components, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *CreateApplicationBodyComponentsItem) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.MaxCPU.SetFake()
		}
	}
	{
		{
			s.MaxMemory.SetFake()
		}
	}
	{
		{
			s.DeploySource.SetFake()
		}
	}
	{
		{
			s.Env.SetFake()
		}
	}
	{
		{
			s.Secret.SetFake()
		}
	}
	{
		{
			s.Probe.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *CreateApplicationBodyComponentsItemDeploySource) SetFake() {
	{
		{
			s.ContainerRegistry.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *CreateApplicationBodyComponentsItemDeploySourceContainerRegistry) SetFake() {
	{
		{
			s.Image = "string"
		}
	}
	{
		{
			s.Server.SetFake()
		}
	}
	{
		{
			s.Username.SetFake()
		}
	}
	{
		{
			s.Password.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *CreateApplicationBodyComponentsItemMaxCPU) SetFake() {
	*s = CreateApplicationBodyComponentsItemMaxCPU05
}

// SetFake set fake values.
func (s *CreateApplicationBodyComponentsItemMaxMemory) SetFake() {
	*s = CreateApplicationBodyComponentsItemMaxMemory1Gi
}

// SetFake set fake values.
func (s *CreateApplicationBodyComponentsItemProbe) SetFake() {
	{
		{
			s.HTTPGet.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *CreateApplicationBodyComponentsItemProbeHTTPGet) SetFake() {
	{
		{
			s.Path = "string"
		}
	}
	{
		{
			s.Port = int(0)
		}
	}
	{
		{
			s.Headers = nil
			for i := 0; i < 0; i++ {
				var elem CreateApplicationBodyComponentsItemProbeHTTPGetHeadersItem
				{
					elem.SetFake()
				}
				s.Headers = append(s.Headers, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *CreateApplicationBodyComponentsItemProbeHTTPGetHeadersItem) SetFake() {
	{
		{
			s.Name.SetFake()
		}
	}
	{
		{
			s.Value.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *CreateApplicationBodyComponentsItemSecretItem) SetFake() {
	{
		{
			s.Key = "string"
		}
	}
	{
		{
			s.Value = "string"
		}
	}
}

// SetFake set fake values.
func (s *CreateApplicationConflict) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *CreateApplicationForbidden) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *CreateApplicationInternalServerError) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *CreateApplicationUnauthorized) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *CreateUserConflict) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *CreateUserForbidden) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *CreateUserInternalServerError) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *CreateUserUnauthorized) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *DeleteApplicationBadRequest) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *DeleteApplicationForbidden) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *DeleteApplicationInternalServerError) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *DeleteApplicationNotFound) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *DeleteApplicationUnauthorized) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *DeleteApplicationVersionBadRequest) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *DeleteApplicationVersionForbidden) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *DeleteApplicationVersionInternalServerError) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *DeleteApplicationVersionNotFound) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *DeleteApplicationVersionUnauthorized) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *HandlerCreateApplication) SetFake() {
	{
		{
			s.ID = "string"
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.TimeoutSeconds = int(0)
		}
	}
	{
		{
			s.Port = int(0)
		}
	}
	{
		{
			s.MinScale = int(0)
		}
	}
	{
		{
			s.MaxScale = int(0)
		}
	}
	{
		{
			s.ScaleTargetConcurrency.SetFake()
		}
	}
	{
		{
			s.Components = nil
			for i := 0; i < 0; i++ {
				var elem HandlerCreateApplicationComponentsItem
				{
					elem.SetFake()
				}
				s.Components = append(s.Components, elem)
			}
		}
	}
	{
		{
			s.Status.SetFake()
		}
	}
	{
		{
			s.PublicURL = "string"
		}
	}
	{
		{
			s.ResourceID = "string"
		}
	}
	{
		{
			s.CreatedAt = time.Now()
		}
	}
}

// SetFake set fake values.
func (s *HandlerCreateApplicationComponentsItem) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.MaxCPU = "string"
		}
	}
	{
		{
			s.MaxMemory = "string"
		}
	}
	{
		{
			s.DeploySource.SetFake()
		}
	}
	{
		{
			s.Env.SetFake()
		}
	}
	{
		{
			s.Secret.SetFake()
		}
	}
	{
		{
			s.Probe.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *HandlerCreateApplicationComponentsItemDeploySource) SetFake() {
	{
		{
			s.ContainerRegistry.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *HandlerCreateApplicationComponentsItemDeploySourceContainerRegistry) SetFake() {
	{
		{
			s.Image = "string"
		}
	}
	{
		{
			s.Server.SetFake()
		}
	}
	{
		{
			s.Username.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *HandlerCreateApplicationComponentsItemProbe) SetFake() {
	{
		{
			s.HTTPGet.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *HandlerCreateApplicationComponentsItemProbeHTTPGet) SetFake() {
	{
		{
			s.Path = "string"
		}
	}
	{
		{
			s.Port = int(0)
		}
	}
	{
		{
			s.Headers = nil
			for i := 0; i < 0; i++ {
				var elem HandlerCreateApplicationComponentsItemProbeHTTPGetHeadersItem
				{
					elem.SetFake()
				}
				s.Headers = append(s.Headers, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *HandlerCreateApplicationComponentsItemProbeHTTPGetHeadersItem) SetFake() {
	{
		{
			s.Name.SetFake()
		}
	}
	{
		{
			s.Value.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *HandlerCreateApplicationStatus) SetFake() {
	*s = HandlerCreateApplicationStatusHealthy
}

// SetFake set fake values.
func (s *HandlerCreateUser) SetFake() {
	{
		{
			s.Limit.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *HandlerCreateUserLimit) SetFake() {
	{
		{
			s.ApplicationCount = int(0)
		}
	}
}

// SetFake set fake values.
func (s *HandlerListApplications) SetFake() {
	{
		{
			s.Meta.SetFake()
		}
	}
	{
		{
			s.Data = nil
			for i := 0; i < 0; i++ {
				var elem HandlerListApplicationsDataItem
				{
					elem.SetFake()
				}
				s.Data = append(s.Data, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *HandlerListApplicationsDataItem) SetFake() {
	{
		{
			s.ID = "string"
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Status.SetFake()
		}
	}
	{
		{
			s.PublicURL = "string"
		}
	}
	{
		{
			s.CreatedAt = time.Now()
		}
	}
}

// SetFake set fake values.
func (s *HandlerListApplicationsDataItemStatus) SetFake() {
	*s = HandlerListApplicationsDataItemStatusHealthy
}

// SetFake set fake values.
func (s *HandlerListApplicationsMeta) SetFake() {
	{
		{
			s.PageNum = int(0)
		}
	}
	{
		{
			s.PageSize = int(0)
		}
	}
	{
		{
			s.ObjectTotal = int(0)
		}
	}
	{
		{
			s.SortField = "string"
		}
	}
	{
		{
			s.SortOrder.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *HandlerListApplicationsMetaSortOrder) SetFake() {
	*s = HandlerListApplicationsMetaSortOrderAsc
}

// SetFake set fake values.
func (s *HandlerListTraffic) SetFake() {
	{
		{
			s.Meta.SetFake()
		}
	}
	{
		{
			s.Data = nil
			for i := 0; i < 0; i++ {
				var elem HandlerListTrafficDataItem
				{
					elem.SetFake()
				}
				s.Data = append(s.Data, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *HandlerListTrafficDataItem) SetFake() {
	{
		{
			s.VersionName = "string"
		}
	}
	{
		{
			s.IsLatestVersion = true
		}
	}
	{
		{
			s.Percent = int(0)
		}
	}
}

// SetFake set fake values.
func (s *HandlerListTrafficMeta) SetFake() {
}

// SetFake set fake values.
func (s *HandlerListVersions) SetFake() {
	{
		{
			s.Meta.SetFake()
		}
	}
	{
		{
			s.Data = nil
			for i := 0; i < 0; i++ {
				var elem HandlerListVersionsDataItem
				{
					elem.SetFake()
				}
				s.Data = append(s.Data, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *HandlerListVersionsDataItem) SetFake() {
	{
		{
			s.ID = "string"
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Status.SetFake()
		}
	}
	{
		{
			s.CreatedAt = time.Now()
		}
	}
}

// SetFake set fake values.
func (s *HandlerListVersionsDataItemStatus) SetFake() {
	*s = HandlerListVersionsDataItemStatusHealthy
}

// SetFake set fake values.
func (s *HandlerListVersionsMeta) SetFake() {
	{
		{
			s.PageNum = int(0)
		}
	}
	{
		{
			s.PageSize = int(0)
		}
	}
	{
		{
			s.ObjectTotal = int(0)
		}
	}
	{
		{
			s.SortField = "string"
		}
	}
	{
		{
			s.SortOrder.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *HandlerListVersionsMetaSortOrder) SetFake() {
	*s = HandlerListVersionsMetaSortOrderAsc
}

// SetFake set fake values.
func (s *HandlerPatchApplication) SetFake() {
	{
		{
			s.ID = "string"
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.TimeoutSeconds = int(0)
		}
	}
	{
		{
			s.Port = int(0)
		}
	}
	{
		{
			s.MinScale = int(0)
		}
	}
	{
		{
			s.MaxScale = int(0)
		}
	}
	{
		{
			s.ScaleTargetConcurrency.SetFake()
		}
	}
	{
		{
			s.Components = nil
			for i := 0; i < 0; i++ {
				var elem HandlerPatchApplicationComponentsItem
				{
					elem.SetFake()
				}
				s.Components = append(s.Components, elem)
			}
		}
	}
	{
		{
			s.Status.SetFake()
		}
	}
	{
		{
			s.PublicURL = "string"
		}
	}
	{
		{
			s.ResourceID = "string"
		}
	}
	{
		{
			s.UpdatedAt = time.Now()
		}
	}
}

// SetFake set fake values.
func (s *HandlerPatchApplicationComponentsItem) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.MaxCPU = "string"
		}
	}
	{
		{
			s.MaxMemory = "string"
		}
	}
	{
		{
			s.DeploySource.SetFake()
		}
	}
	{
		{
			s.Env.SetFake()
		}
	}
	{
		{
			s.Secret.SetFake()
		}
	}
	{
		{
			s.Probe.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *HandlerPatchApplicationComponentsItemDeploySource) SetFake() {
	{
		{
			s.ContainerRegistry.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *HandlerPatchApplicationComponentsItemDeploySourceContainerRegistry) SetFake() {
	{
		{
			s.Image = "string"
		}
	}
	{
		{
			s.Server.SetFake()
		}
	}
	{
		{
			s.Username.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *HandlerPatchApplicationComponentsItemProbe) SetFake() {
	{
		{
			s.HTTPGet.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *HandlerPatchApplicationComponentsItemProbeHTTPGet) SetFake() {
	{
		{
			s.Path = "string"
		}
	}
	{
		{
			s.Port = int(0)
		}
	}
	{
		{
			s.Headers = nil
			for i := 0; i < 0; i++ {
				var elem HandlerPatchApplicationComponentsItemProbeHTTPGetHeadersItem
				{
					elem.SetFake()
				}
				s.Headers = append(s.Headers, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *HandlerPatchApplicationComponentsItemProbeHTTPGetHeadersItem) SetFake() {
	{
		{
			s.Name.SetFake()
		}
	}
	{
		{
			s.Value.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *HandlerPatchApplicationStatus) SetFake() {
	*s = HandlerPatchApplicationStatusHealthy
}

// SetFake set fake values.
func (s *HandlerPatchPacketFilter) SetFake() {
	{
		{
			s.IsEnabled = true
		}
	}
	{
		{
			s.Settings = nil
			for i := 0; i < 0; i++ {
				var elem HandlerPatchPacketFilterSettingsItem
				{
					elem.SetFake()
				}
				s.Settings = append(s.Settings, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *HandlerPatchPacketFilterSettingsItem) SetFake() {
	{
		{
			s.FromIP = "string"
		}
	}
	{
		{
			s.FromIPPrefixLength = int(0)
		}
	}
}

// SetFake set fake values.
func (s *HandlerReadApplication) SetFake() {
	{
		{
			s.ID = "string"
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.TimeoutSeconds = int(0)
		}
	}
	{
		{
			s.Port = int(0)
		}
	}
	{
		{
			s.MinScale = int(0)
		}
	}
	{
		{
			s.MaxScale = int(0)
		}
	}
	{
		{
			s.ScaleTargetConcurrency.SetFake()
		}
	}
	{
		{
			s.Components = nil
			for i := 0; i < 0; i++ {
				var elem HandlerReadApplicationComponentsItem
				{
					elem.SetFake()
				}
				s.Components = append(s.Components, elem)
			}
		}
	}
	{
		{
			s.Status.SetFake()
		}
	}
	{
		{
			s.PublicURL = "string"
		}
	}
	{
		{
			s.ResourceID = "string"
		}
	}
	{
		{
			s.CreatedAt = time.Now()
		}
	}
}

// SetFake set fake values.
func (s *HandlerReadApplicationComponentsItem) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.MaxCPU = "string"
		}
	}
	{
		{
			s.MaxMemory = "string"
		}
	}
	{
		{
			s.DeploySource.SetFake()
		}
	}
	{
		{
			s.Env.SetFake()
		}
	}
	{
		{
			s.Secret.SetFake()
		}
	}
	{
		{
			s.Probe.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *HandlerReadApplicationComponentsItemDeploySource) SetFake() {
	{
		{
			s.ContainerRegistry.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *HandlerReadApplicationComponentsItemDeploySourceContainerRegistry) SetFake() {
	{
		{
			s.Image = "string"
		}
	}
	{
		{
			s.Server.SetFake()
		}
	}
	{
		{
			s.Username.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *HandlerReadApplicationComponentsItemProbe) SetFake() {
	{
		{
			s.HTTPGet.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *HandlerReadApplicationComponentsItemProbeHTTPGet) SetFake() {
	{
		{
			s.Path = "string"
		}
	}
	{
		{
			s.Port = int(0)
		}
	}
	{
		{
			s.Headers = nil
			for i := 0; i < 0; i++ {
				var elem HandlerReadApplicationComponentsItemProbeHTTPGetHeadersItem
				{
					elem.SetFake()
				}
				s.Headers = append(s.Headers, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *HandlerReadApplicationComponentsItemProbeHTTPGetHeadersItem) SetFake() {
	{
		{
			s.Name.SetFake()
		}
	}
	{
		{
			s.Value.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *HandlerReadApplicationOnlyStatus) SetFake() {
	{
		{
			s.Status.SetFake()
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *HandlerReadApplicationOnlyStatusStatus) SetFake() {
	*s = HandlerReadApplicationOnlyStatusStatusHealthy
}

// SetFake set fake values.
func (s *HandlerReadApplicationStatus) SetFake() {
	*s = HandlerReadApplicationStatusHealthy
}

// SetFake set fake values.
func (s *HandlerReadApplicationVersionOnlyStatus) SetFake() {
	{
		{
			s.Status.SetFake()
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *HandlerReadApplicationVersionOnlyStatusStatus) SetFake() {
	*s = HandlerReadApplicationVersionOnlyStatusStatusHealthy
}

// SetFake set fake values.
func (s *HandlerReadPacketFilter) SetFake() {
	{
		{
			s.IsEnabled = true
		}
	}
	{
		{
			s.Settings = nil
			for i := 0; i < 0; i++ {
				var elem HandlerReadPacketFilterSettingsItem
				{
					elem.SetFake()
				}
				s.Settings = append(s.Settings, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *HandlerReadPacketFilterSettingsItem) SetFake() {
	{
		{
			s.FromIP = "string"
		}
	}
	{
		{
			s.FromIPPrefixLength = int(0)
		}
	}
}

// SetFake set fake values.
func (s *HandlerReadUser) SetFake() {
	{
		{
			s.Limit.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *HandlerReadUserLimit) SetFake() {
	{
		{
			s.ApplicationCount = int(0)
		}
	}
}

// SetFake set fake values.
func (s *HandlerReadVersion) SetFake() {
	{
		{
			s.ID = "string"
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Status.SetFake()
		}
	}
	{
		{
			s.TimeoutSeconds = int(0)
		}
	}
	{
		{
			s.Port = int(0)
		}
	}
	{
		{
			s.MinScale = int(0)
		}
	}
	{
		{
			s.MaxScale = int(0)
		}
	}
	{
		{
			s.ScaleTargetConcurrency.SetFake()
		}
	}
	{
		{
			s.Components = nil
			for i := 0; i < 0; i++ {
				var elem HandlerReadVersionComponentsItem
				{
					elem.SetFake()
				}
				s.Components = append(s.Components, elem)
			}
		}
	}
	{
		{
			s.CreatedAt = time.Now()
		}
	}
}

// SetFake set fake values.
func (s *HandlerReadVersionComponentsItem) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.MaxCPU = "string"
		}
	}
	{
		{
			s.MaxMemory = "string"
		}
	}
	{
		{
			s.DeploySource.SetFake()
		}
	}
	{
		{
			s.Env.SetFake()
		}
	}
	{
		{
			s.Secret.SetFake()
		}
	}
	{
		{
			s.Probe.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *HandlerReadVersionComponentsItemDeploySource) SetFake() {
	{
		{
			s.ContainerRegistry.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *HandlerReadVersionComponentsItemDeploySourceContainerRegistry) SetFake() {
	{
		{
			s.Image = "string"
		}
	}
	{
		{
			s.Server.SetFake()
		}
	}
	{
		{
			s.Username.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *HandlerReadVersionComponentsItemProbe) SetFake() {
	{
		{
			s.HTTPGet.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *HandlerReadVersionComponentsItemProbeHTTPGet) SetFake() {
	{
		{
			s.Path = "string"
		}
	}
	{
		{
			s.Port = int(0)
		}
	}
	{
		{
			s.Headers = nil
			for i := 0; i < 0; i++ {
				var elem HandlerReadVersionComponentsItemProbeHTTPGetHeadersItem
				{
					elem.SetFake()
				}
				s.Headers = append(s.Headers, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *HandlerReadVersionComponentsItemProbeHTTPGetHeadersItem) SetFake() {
	{
		{
			s.Name.SetFake()
		}
	}
	{
		{
			s.Value.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *HandlerReadVersionStatus) SetFake() {
	*s = HandlerReadVersionStatusHealthy
}

// SetFake set fake values.
func (s *HandlerUpdateTraffic) SetFake() {
	{
		{ // Keep pointer nil to prevent infinite recursion.
			s.Meta = nil
		}
	}
	{
		{
			s.Data = nil
			for i := 0; i < 0; i++ {
				var elem HandlerUpdateTrafficDataItem
				{
					elem.SetFake()
				}
				s.Data = append(s.Data, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *HandlerUpdateTrafficDataItem) SetFake() {
	{
		{
			s.VersionName = "string"
		}
	}
	{
		{
			s.IsLatestVersion = true
		}
	}
	{
		{
			s.Percent = int(0)
		}
	}
}

// SetFake set fake values.
func (s *HandlerUpdateTrafficMeta) SetFake() {
}

// SetFake set fake values.
func (s *ListApplicationTrafficBadRequest) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *ListApplicationTrafficForbidden) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *ListApplicationTrafficInternalServerError) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *ListApplicationTrafficNotFound) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *ListApplicationTrafficUnauthorized) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *ListApplicationVersionsBadRequest) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *ListApplicationVersionsForbidden) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *ListApplicationVersionsInternalServerError) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *ListApplicationVersionsNotFound) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *ListApplicationVersionsUnauthorized) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *ListApplicationsBadRequest) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *ListApplicationsForbidden) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *ListApplicationsInternalServerError) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *ListApplicationsUnauthorized) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *ModelCloudctrlError) SetFake() {
	{
		{
			s.IsFatal = true
		}
	}
	{
		{
			s.Serial = "string"
		}
	}
	{
		{
			s.Status = "string"
		}
	}
	{
		{
			s.ErrorCode = "string"
		}
	}
	{
		{
			s.ErrorMsg = "string"
		}
	}
}

// SetFake set fake values.
func (s *ModelDefaultError) SetFake() {
	{
		{
			s.Error.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ModelDefaultErrorError) SetFake() {
	{
		{
			s.Code = int(0)
		}
	}
	{
		{
			s.Message = "string"
		}
	}
	{
		{
			s.Errors.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ModelErrors) SetFake() {
	var unwrapped []ModelErrorsItem
	{
		unwrapped = nil
		for i := 0; i < 0; i++ {
			var elem ModelErrorsItem
			{
				elem.SetFake()
			}
			unwrapped = append(unwrapped, elem)
		}
	}
	*s = ModelErrors(unwrapped)
}

// SetFake set fake values.
func (s *ModelErrorsItem) SetFake() {
	{
		{
			s.Domain.SetFake()
		}
	}
	{
		{
			s.Reason.SetFake()
		}
	}
	{
		{
			s.Message.SetFake()
		}
	}
	{
		{
			s.LocationType.SetFake()
		}
	}
	{
		{
			s.Location.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ModelErrorsItemLocationType) SetFake() {
	*s = ModelErrorsItemLocationTypeHeader
}

// SetFake set fake values.
func (s *NilString) SetFake() {
	s.Null = true
}

// SetFake set fake values.
func (s *OptBool) SetFake() {
	var elem bool
	{
		elem = true
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptCreateApplicationBodyComponentsItemDeploySourceContainerRegistry) SetFake() {
	var elem CreateApplicationBodyComponentsItemDeploySourceContainerRegistry
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptHandlerCreateApplicationComponentsItemDeploySourceContainerRegistry) SetFake() {
	var elem HandlerCreateApplicationComponentsItemDeploySourceContainerRegistry
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptHandlerListTrafficMeta) SetFake() {
	var elem *HandlerListTrafficMeta
	{ // Keep pointer nil to prevent infinite recursion.
		elem = nil
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptHandlerPatchApplicationComponentsItemDeploySourceContainerRegistry) SetFake() {
	var elem HandlerPatchApplicationComponentsItemDeploySourceContainerRegistry
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptHandlerReadApplicationComponentsItemDeploySourceContainerRegistry) SetFake() {
	var elem HandlerReadApplicationComponentsItemDeploySourceContainerRegistry
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptHandlerReadVersionComponentsItemDeploySourceContainerRegistry) SetFake() {
	var elem HandlerReadVersionComponentsItemDeploySourceContainerRegistry
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptInt) SetFake() {
	var elem int
	{
		elem = int(0)
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptNilContainerRegistryAction) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilCreateApplicationBodyComponentsItemProbe) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilCreateApplicationBodyComponentsItemProbeHTTPGet) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilCreateApplicationBodyComponentsItemSecretItemArray) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilHandlerCreateApplicationComponentsItemProbe) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilHandlerCreateApplicationComponentsItemProbeHTTPGet) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilHandlerPatchApplicationComponentsItemProbe) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilHandlerPatchApplicationComponentsItemProbeHTTPGet) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilHandlerReadApplicationComponentsItemProbe) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilHandlerReadApplicationComponentsItemProbeHTTPGet) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilHandlerReadVersionComponentsItemProbe) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilHandlerReadVersionComponentsItemProbeHTTPGet) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilModelErrorsItemLocationType) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilPatchApplicationBodyComponentsItemProbe) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilPatchApplicationBodyComponentsItemProbeHTTPGet) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilPatchApplicationBodyComponentsItemSecretItemArray) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilRequestEnv) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilString) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptPatchApplicationBodyComponentsItemDeploySourceContainerRegistry) SetFake() {
	var elem PatchApplicationBodyComponentsItemDeploySourceContainerRegistry
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptString) SetFake() {
	var elem string
	{
		elem = "string"
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *PatchApplicationBadRequest) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *PatchApplicationBody) SetFake() {
	{
		{
			s.TimeoutSeconds.SetFake()
		}
	}
	{
		{
			s.Port.SetFake()
		}
	}
	{
		{
			s.MinScale.SetFake()
		}
	}
	{
		{
			s.MaxScale.SetFake()
		}
	}
	{
		{
			s.ScaleTargetConcurrency.SetFake()
		}
	}
	{
		{
			s.Components = nil
			for i := 0; i < 0; i++ {
				var elem PatchApplicationBodyComponentsItem
				{
					elem.SetFake()
				}
				s.Components = append(s.Components, elem)
			}
		}
	}
	{
		{
			s.AllTrafficAvailable.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PatchApplicationBodyComponentsItem) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.MaxCPU.SetFake()
		}
	}
	{
		{
			s.MaxMemory.SetFake()
		}
	}
	{
		{
			s.DeploySource.SetFake()
		}
	}
	{
		{
			s.Env.SetFake()
		}
	}
	{
		{
			s.Secret.SetFake()
		}
	}
	{
		{
			s.Probe.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PatchApplicationBodyComponentsItemDeploySource) SetFake() {
	{
		{
			s.ContainerRegistry.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PatchApplicationBodyComponentsItemDeploySourceContainerRegistry) SetFake() {
	{
		{
			s.Image = "string"
		}
	}
	{
		{
			s.Server.SetFake()
		}
	}
	{
		{
			s.Username.SetFake()
		}
	}
	{
		{
			s.Password.SetFake()
		}
	}
	{
		{
			s.Action.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PatchApplicationBodyComponentsItemMaxCPU) SetFake() {
	*s = PatchApplicationBodyComponentsItemMaxCPU05
}

// SetFake set fake values.
func (s *PatchApplicationBodyComponentsItemMaxMemory) SetFake() {
	*s = PatchApplicationBodyComponentsItemMaxMemory1Gi
}

// SetFake set fake values.
func (s *PatchApplicationBodyComponentsItemProbe) SetFake() {
	{
		{
			s.HTTPGet.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PatchApplicationBodyComponentsItemProbeHTTPGet) SetFake() {
	{
		{
			s.Path = "string"
		}
	}
	{
		{
			s.Port = int(0)
		}
	}
	{
		{
			s.Headers = nil
			for i := 0; i < 0; i++ {
				var elem PatchApplicationBodyComponentsItemProbeHTTPGetHeadersItem
				{
					elem.SetFake()
				}
				s.Headers = append(s.Headers, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *PatchApplicationBodyComponentsItemProbeHTTPGetHeadersItem) SetFake() {
	{
		{
			s.Name.SetFake()
		}
	}
	{
		{
			s.Value.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PatchApplicationBodyComponentsItemSecretItem) SetFake() {
	{
		{
			s.Key = "string"
		}
	}
	{
		{
			s.Value.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PatchApplicationConflict) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *PatchApplicationForbidden) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *PatchApplicationInternalServerError) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *PatchApplicationNotFound) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *PatchApplicationPacketFilterBadRequest) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *PatchApplicationPacketFilterForbidden) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *PatchApplicationPacketFilterInternalServerError) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *PatchApplicationPacketFilterNotFound) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *PatchApplicationPacketFilterUnauthorized) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *PatchApplicationUnauthorized) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *PatchPacketFilterBody) SetFake() {
	{
		{
			s.IsEnabled.SetFake()
		}
	}
	{
		{
			s.Settings = nil
			for i := 0; i < 0; i++ {
				var elem PatchPacketFilterBodySettingsItem
				{
					elem.SetFake()
				}
				s.Settings = append(s.Settings, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *PatchPacketFilterBodySettingsItem) SetFake() {
	{
		{
			s.FromIP = "string"
		}
	}
	{
		{
			s.FromIPPrefixLength = int(0)
		}
	}
}

// SetFake set fake values.
func (s *ReadApplicationBadRequest) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *ReadApplicationForbidden) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *ReadApplicationInternalServerError) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *ReadApplicationNotFound) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *ReadApplicationPacketFilterBadRequest) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *ReadApplicationPacketFilterForbidden) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *ReadApplicationPacketFilterInternalServerError) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *ReadApplicationPacketFilterNotFound) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *ReadApplicationPacketFilterUnauthorized) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *ReadApplicationStatusBadRequest) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *ReadApplicationStatusForbidden) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *ReadApplicationStatusInternalServerError) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *ReadApplicationStatusNotFound) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *ReadApplicationStatusUnauthorized) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *ReadApplicationUnauthorized) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *ReadApplicationVersionBadRequest) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *ReadApplicationVersionForbidden) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *ReadApplicationVersionInternalServerError) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *ReadApplicationVersionNotFound) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *ReadApplicationVersionStatusBadRequest) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *ReadApplicationVersionStatusForbidden) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *ReadApplicationVersionStatusInternalServerError) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *ReadApplicationVersionStatusNotFound) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *ReadApplicationVersionStatusUnauthorized) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *ReadApplicationVersionUnauthorized) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *ReadUserForbidden) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *ReadUserInternalServerError) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *ReadUserNotFound) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *ReadUserUnauthorized) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *RequestEnv) SetFake() {
	var unwrapped []RequestEnvItem
	{
		unwrapped = nil
		for i := 0; i < 0; i++ {
			var elem RequestEnvItem
			{
				elem.SetFake()
			}
			unwrapped = append(unwrapped, elem)
		}
	}
	*s = RequestEnv(unwrapped)
}

// SetFake set fake values.
func (s *RequestEnvItem) SetFake() {
	{
		{
			s.Key = "string"
		}
	}
	{
		{
			s.Value = "string"
		}
	}
}

// SetFake set fake values.
func (s *ResponseEnv) SetFake() {
	var unwrapped []ResponseEnvItem
	{
		unwrapped = nil
		for i := 0; i < 0; i++ {
			var elem ResponseEnvItem
			{
				elem.SetFake()
			}
			unwrapped = append(unwrapped, elem)
		}
	}
	*s = ResponseEnv(unwrapped)
}

// SetFake set fake values.
func (s *ResponseEnvItem) SetFake() {
	{
		{
			s.Key = "string"
		}
	}
	{
		{
			s.Value = "string"
		}
	}
}

// SetFake set fake values.
func (s *ResponseSecret) SetFake() {
	var unwrapped []ResponseSecretItem
	{
		unwrapped = nil
		for i := 0; i < 0; i++ {
			var elem ResponseSecretItem
			{
				elem.SetFake()
			}
			unwrapped = append(unwrapped, elem)
		}
	}
	*s = ResponseSecret(unwrapped)
}

// SetFake set fake values.
func (s *ResponseSecretItem) SetFake() {
	{
		{
			s.Key = "string"
		}
	}
}

// SetFake set fake values.
func (s *UpdateApplicationTrafficBadRequest) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *UpdateApplicationTrafficForbidden) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *UpdateApplicationTrafficInternalServerError) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *UpdateApplicationTrafficNotFound) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *UpdateApplicationTrafficUnauthorized) SetFake() {
	var variant ModelDefaultError

	{
		variant.SetFake()
	}
	s.SetModelDefaultError(variant)
}

// SetFake set fake values.
func (s *UpdateTrafficBody) SetFake() {
	var unwrapped []UpdateTrafficBodyItem
	{
		unwrapped = nil
		for i := 0; i < 0; i++ {
			var elem UpdateTrafficBodyItem
			{
				elem.SetFake()
			}
			unwrapped = append(unwrapped, elem)
		}
	}
	*s = UpdateTrafficBody(unwrapped)
}

// SetFake set fake values.
func (s *UpdateTrafficBodyItem) SetFake() {
	var variant UpdateTrafficBodyItem0

	{
		variant.SetFake()
	}
	s.SetUpdateTrafficBodyItem0(variant)
}

// SetFake set fake values.
func (s *UpdateTrafficBodyItem0) SetFake() {
	{
		{
			s.IsLatestVersion = true
		}
	}
	{
		{
			s.Percent = int(0)
		}
	}
}

// SetFake set fake values.
func (s *UpdateTrafficBodyItem1) SetFake() {
	{
		{
			s.VersionName = "string"
		}
	}
	{
		{
			s.Percent = int(0)
		}
	}
}
