// Code generated by ogen, DO NOT EDIT.

package queue

// OperationName is the ogen operation name
type OperationName = string

const (
	ClearQueueOperation       OperationName = "ClearQueue"
	CreateQueueOperation      OperationName = "CreateQueue"
	DeleteQueueOperation      OperationName = "DeleteQueue"
	ListQueuesOperation       OperationName = "ListQueues"
	ReadMessageCountOperation OperationName = "ReadMessageCount"
	ReadQueueOperation        OperationName = "ReadQueue"
	RotateAPIKeyOperation     OperationName = "RotateAPIKey"
	UpdateQueueOperation      OperationName = "UpdateQueue"
)
