# Copyright 2026- The sacloud/sacloud-sdk-go Authors
# SPDX-License-Identifier: Apache-2.0

name: Tests
on: [push, pull_request]

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: read
    outputs:
      changes: ${{ steps.filter.outputs.changes }}
    steps:
      # Note that `dorny/paths-filter` itself runs without `actions/checkout`
      # but the `git ls-files` below mandates `.git` to exist.
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: list submodules
        id: submodules
        run: >-
          echo 'submodules<<EOF' >> "${GITHUB_OUTPUT}" ;
          git ls-files                                 |
          grep /Makefile                               |
          sed 's/\/Makefile//'                         |
          sort -u                                      |
          xargs -I{} printf '%s:\n  - %s/**\n  - go.mod\n  - go.sum\n  - .github/workflows/tests.yaml\n' {} {}
          >> "${GITHUB_OUTPUT}"                        ;
          echo 'EOF' >> "${GITHUB_OUTPUT}"
      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: filter
        with:
          filters: ${{ steps.submodules.outputs.submodules }}

  lint-text:
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.changes != '[]'
    strategy:
      fail-fast: false
      matrix:
        module: ${{ fromJSON(needs.changes.outputs.changes) }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: sacloud/textlint-action@f0e5128aff22b8ce29ceb9b053dda71303f3f0a9 # v0.1.1
        with:
          working-directory: ${{ matrix.module }}

  lint-go:
    runs-on: ubuntu-latest
    needs: changes
    if: >-
      needs.changes.outputs.changes != '[]' &&
      github.event_name == 'pull_request'
    strategy:
      fail-fast: false
      matrix:
        module: ${{ fromJSON(needs.changes.outputs.changes) }}
    permissions:
      pull-requests: read
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
      - uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # v9.2.1
        with:
          version: latest
          working-directory: ${{ matrix.module }}
          only-new-issues: true
          args: --timeout 5m

  vulncheck:
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.changes != '[]'
    strategy:
      fail-fast: false
      matrix:
        module: ${{ fromJSON(needs.changes.outputs.changes) }}
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      # Somehow `golang/govulncheck-action` does not make releases for years.
      # We just pin the commit SHA.
      - uses: golang/govulncheck-action@032d45514ae346b1db93c04b0c90b841c370344f
        with:
          go-version-file: go.mod
          go-version-input: ''
          work-dir: ${{ matrix.module }}
          repo-checkout: false
          output-format: sarif
          output-file: govulncheck.sarif
      - uses: github/codeql-action/upload-sarif@7211b7c8077ea37d8641b6271f6a365a22a5fbfa # v4.36.0
        with:
          sarif_file: govulncheck.sarif

  test:
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.changes != '[]'
    strategy:
      fail-fast: false
      matrix:
        module: ${{ fromJSON(needs.changes.outputs.changes) }}
        go-version:
          - stable
          - oldstable
    defaults:
      run:
        working-directory: ${{ matrix.module }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: ${{ matrix.go-version }}
      - run: make tools
      - run: make test
